### ISSUE TITLE
Get blog page working

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#1]
The blog posts have been migrated over but we need an actual blog page to load the different post contents.

**Comment by jorgemgoncalves** [comment]
The blog is already working. We are adjusting css. 

@yalisassoon For **v2** we should consider defining fixed image sizes for author, full width and videos.

**Comment by yalisassoon** [comment]
Great! Closing this issue in favour of more specific tickets e.g. https://github.com/snowplow/snowplowanalytics.com/issues/40 and https://github.com/snowplow/snowplowanalytics.com/issues/39
