### ISSUE TITLE
Add SSL cert to collector-rt.snplow.com

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#102]
So we can put our demo pipeline live! (Otherwise breaks HTTPS.)

This is not part of the v1 milestone @jbeemster so no rush to get it done.

**Comment by jbeemster** [comment]
You mean: http://collector-rt-demo.snplow.com/ ?

**Comment by jbeemster** [comment]
Also @alexanderdean please share the `*.snplow.com` certificate details with me so I can action this.

**Comment by alexanderdean** [comment]
Shared!

**Comment by jbeemster** [comment]
This has been done - can be re-added to the website now.

**Comment by bogaert** [comment]
Done. Closing.
