### ISSUE TITLE
New logo image files

### ISSUE THREAD

**Issue by dilyand** [snowplow/snowplowanalytics.com#111]
Where can I grab different versions (small, large, white, black, etc) of the new Snowplow logo?

**Comment by yalisassoon** [comment]
@jorgemgoncalves can you please help here? We want to put the new logo live on discourse.snowplowanalytics.com

**Comment by jorgemgoncalves** [comment]
@yalisassoon and @dilyand we'll have a logo suite ready for you in no time. 

For now here is the snowplow white logo in svg and the background-color should be #9014477

[Snowplow_Website-Logo_Menu_White.svg.zip](https://github.com/snowplow/snowplowanalytics.com/files/958007/Snowplow_Website-Logo_Menu_White.svg.zip)
