### ISSUE TITLE
Change from Snowplow pipeline to Snowplow Insights

### ISSUE THREAD

**Issue by idanby1** [snowplow/snowplowanalytics.com#113]
In https://snowplowanalytics.com/assets/pdf/Snowplow-VS-SaaS_Data_Warehouse_Providers.pdf Page 3 need to change from:

A formal approach to handling bad data. Bad data is a fact of life. The
**Snowplow pipeline** has a formal validation step: where input data is validated 

To:

A formal approach to handling bad data. Bad data is a fact of life. **Snowplow Insights** has a formal validation step: where input data is validated

**Comment by jorgemgoncalves** [comment]
PDF corrections placed online in the develop branch. Please review.

**Comment by yalisassoon** [comment]
Sorry @jorgemgoncalves - this needs another update. It is currently

> "The Snowplow Insights has a formal"

It should be

> "Snowplow Insights has a formal"

(We need to drop the "The".)

**Comment by yalisassoon** [comment]
@jorgemgoncalves - this still appears to be an issue (see the sentence starts with "The":

![image](https://cloud.githubusercontent.com/assets/201147/25809588/5c6d79cc-3405-11e7-8ddf-507996a97c41.png)

**Comment by jorgemgoncalves** [comment]
@yalisassoon We've corrected and update the file. Please confirm.

**Comment by yalisassoon** [comment]
Looks great! Thanks
