### ISSUE TITLE
Subscribe button's height doesn't match input's height

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplowanalytics.com#115]
Only in Firefox on macOS/Linux.

![2017-04-25 21 06 41](https://cloud.githubusercontent.com/assets/681171/25389750/a378b020-29fb-11e7-993f-92faaf58bec5.png)

**Comment by jorgemgoncalves** [comment]
@chuwy Thank you very much for the warning! Problem solution committed in the develop branch.
