### ISSUE TITLE
Not all author photos are shown in blog posts

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplowanalytics.com#116]
Cannot see at least @ggaviani. Seems like URL in img src is capitalized (/assets/img/team/Giuseppe.jpg) while only lower-cased exists. 

![2017-04-25 21 18 19](https://cloud.githubusercontent.com/assets/681171/25390207/0b925e1c-29fd-11e7-9483-8c97806a5f90.png)

**Comment by yalisassoon** [comment]
Thanks - done!
