### ISSUE TITLE
Change from Snowplow pipeline to Snowplow Insights - take 2

### ISSUE THREAD

**Issue by idanby1** [snowplow/snowplowanalytics.com#117]
In https://snowplowanalytics.com/assets/pdf/Snowplow-VS-SaaS_Data_Warehouse_Providers.pdf Page 3 need to change from:

Auditable. Each stage in the **Snowplow data pipeline** is fully auditable. You
have direct access to the raw collector logs, the output of the validation, 

To:
Auditable. Each stage in the **Snowplow Insights pipeline** is fully auditable. You
have direct access to the raw collector logs, the output of the validation,

**Comment by jorgemgoncalves** [comment]
PDF corrections placed online in the develop branch. Please review.
