### ISSUE TITLE
Change tagline for Sauna

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplowanalytics.com#12]
Currently:

    A decisioning and response platform

Better:

    The decisioning and response platform

For parity with the other two

**Comment by petermonte** [comment]
Where exactly is this string "A decisioning and response platform"? at `pages/products/snowplow-open-source/index.html` at line [69](https://github.com/snowplow/snowplowanalytics.com/blob/develop/pages/products/snowplow-open-source/index.html#L69) you can see "THE OPEN SOURCE DECISIONING AND RESPONSE PLATFORM".

**Comment by alexanderdean** [comment]
Already fixed, closing
