### ISSUE TITLE
Fix logo on discourse

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#120]
@jorgemgoncalves - would it be possible to get a copy of the logo for discourse.snowplowanalytics.com?

We'll ask you guys to do a full skin of this at some stage in the next few couple of months. (Still want to concentrate on the main website at the moment.)

Thanks!

**Comment by dilyand** [comment]
FYI, Discourse only accepts .jpg, .jpeg, .png or .gif.

**Comment by jorgemgoncalves** [comment]
Please check if this works. 

![snowplow_website-logo_menu_white](https://cloud.githubusercontent.com/assets/26622929/25448502/919967a4-2ab0-11e7-9359-f8771439bc62.png)

**Comment by dilyand** [comment]
Done.
