### ISSUE TITLE
Fix logo when sharing links from site on social media or in chat clients

### ISSUE THREAD

**Issue by dilyand** [snowplow/snowplowanalytics.com#123]
Whenever a link to the website is shared on social media or in chat clients (such as HipChat), the auto-generated preview uses a version of the logo that has the final w in Snowplow slanted.

**Comment by yalisassoon** [comment]
@jorgemgoncalves I expect this is to do with one of the metatags on the page template?

**Comment by jorgemgoncalves** [comment]
@dilyand Thank you very much for noticing! This passed right through our radars! Image replaced.
