### ISSUE TITLE
Typos on white paper Snowplow VS SaaS load-your-data warehouse providers

### ISSUE THREAD

**Issue by ggaviani** [snowplow/snowplowanalytics.com#124]
I have found the following typos in this pdf:

Page 2
current text: "Today the value is value of warehousing your digital event data ..."
proposed text (eliminate "is value" - repetition): "Today the value of warehousing your digital event data ..."

Page 5
current text: "Weather enrichment: identify the what the weather was like when the event occurred"
proposed text (eliminate "the" before "what"): "Weather enrichment: identify what the weather was like when the event occurred"

**Comment by jorgemgoncalves** [comment]
PDF corrections placed online in the develop branch. Please review.

**Comment by yalisassoon** [comment]
Hey @jbeemster - the folks at Monarqa have updated the PDF. However, whenever I try and redownload it I get the old version.

I've double checked and it's the new version that is in the repo.

Is their a cache invalidation step that we need to take and have missed? (Maybe because it is a PDF?)

Thanks!

**Comment by jbeemster** [comment]
How long ago did you upload it before attempting to re-download?  The invalidation can take a bit of time to finish.

**Comment by yalisassoon** [comment]
Days ago...

**Comment by yalisassoon** [comment]
Actually I think I was mistaken. Looking at the PDFs in the repo it looks like the update to the PDF wasn't made. Reassigning to @jorgemgoncalves to take another look - @jorgemgoncalves we still have

> Today the value is value of warehousing

Rather than

> Today the value of warehousing

on page 2 of the PDF...

**Comment by jorgemgoncalves** [comment]
My bad! I've had placed the new PDF with a wrong filename 😅 ...everything is correct now. Sorry...

**Comment by yalisassoon** [comment]
Looks great! Thanks
