### ISSUE TITLE
Typos & changes for white paper Snowplow VS Build-Your-Own Data Pipeline 

### ISSUE THREAD

**Issue by ggaviani** [snowplow/snowplowanalytics.com#125]
I have found in this pdf the following typos and text I propose to change.

Page 3
Current text: WE BELIEVE THAT SNOWPLOW INSIGHTS OFFERS ALL THE BENEFITS ASSOCIATED WITH BUILDING OUR OWN EVENT DATA PIPELINE BUT WITH A NUMBER OF SIGNIFICANT ADVANTAGES
Proposed text (see bold - I would refer to the pipeline as yours, not ours, as it refers to the user's): WE BELIEVE THAT SNOWPLOW INSIGHTS OFFERS ALL THE BENEFITS ASSOCIATED WITH BUILDING **YOUR** OWN EVENT DATA PIPELINE BUT WITH A NUMBER OF SIGNIFICANT ADVANTAGES

Current text: "How do you evolve your data pipeline with your business as it
changes? H ow do you ensure your analytics stack keeps up with your
business?"
Action: Eliminate space between H and ow

Page 7
Current text: "Our team will be there, either to recover the pipeline (if e.g. it is the result of
an AWS outage) or to advise (if it’s a data collection issue that needs to be addressed
Action: add closing round bracket ")"

**Comment by jorgemgoncalves** [comment]
PDF corrections placed online in the develop branch. Please review.

**Comment by ggaviani** [comment]
Thanks @jorgemgoncalves . However one of the typos is still there. see below. 

Current text: "How do you evolve your data pipeline with your business as it
changes? H ow do you ensure your analytics stack keeps up with your
business?"
Action: Eliminate space between H and ow

**Comment by jorgemgoncalves** [comment]
@ggaviani I've just uploaded a new version of the PDF to the develop branch. I checked it personally.

**Comment by ggaviani** [comment]
thanks @jorgemgoncalves , it looks good.
