### ISSUE TITLE
Small text changes for Simply Business case study

### ISSUE THREAD

**Issue by ggaviani** [snowplow/snowplowanalytics.com#126]
I would make the following text changes in the pdf:

Page 8
Current text: A/B TEST UPDATES TO PRODUCTS TO ENABLE SYSTEMATIC, DATA-DRIVEN IMPROVEMENTS IN THE USER EXPERIENCE
Proposed text (see bold - I think testing sounds better in this heading): A/B **TESTING** UPDATES TO PRODUCTS TO ENABLE SYSTEMATIC, DATA-DRIVEN IMPROVEMENTS IN THE USER EXPERIENCE

Page 11
Current text: See the presentation slides and video of Dani Solà Lagares, Data Architect at
Simply Business, at a recent Snowplow London Meetup about more information about this.
Proposed text (see bold): See the presentation slides and video of Dani Solà Lagares, Data Architect at
Simply Business, at a recent Snowplow London Meetup **for** more information
about this.

**Comment by yalisassoon** [comment]
Hi @jorgemgoncalves - assigning this to you at the moment.

I'm keen though that we get to the point that we can make tweaks to the case study docs, either by using InDesign or getting the doc in another format. What do you suggest?

**Comment by jorgemgoncalves** [comment]
PDF corrections placed online in the develop branch. Please review.
