### ISSUE TITLE
Create guidelines for images and videos on blog

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#129]

**Comment by yalisassoon** [comment]
@jorgemgoncalves what should those guidelines be?

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon, we've been working on this issue. 

We created some rules that adapt the images' width and height and I believe that these are solved. 

Regarding the Slideshare we still haven't found a solution and we believe that if we "force" changes there may be other issues that pop up. 

We are currently working on a fix for the YouTube embeds.

I'll get back to you with more news soon.

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon we've implemented several CSS rules that will format the images, videos and slideshares. 

Please check if it works for you guys.

**Comment by yalisassoon** [comment]
@jorgemgoncalves can you point at the relevant commits, so I check the right thing? (E.g. should I be checking in next.snowplowanalytics.com or on the live site etc.)

Thanks!
