### ISSUE TITLE
Fix team photos

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#13]
What's the best way of doing this Monarqa team?

**Comment by dangregorio** [comment]
Right now, Idan's photo (in Linkedin) is the one that has the best quality and can be used as a reference.

Ideally, de guidelines are:
- We are aiming for a more natural, real feeling.
- Good lighting. Avoid dark spaces or high contrasts of light/shadow.
- Blurred background. Avoid the same background for all.
- Pose: Relaxed, working, spontaneous. Avoid holiday photos or photos outside the professional environment. Yali background photo (website) is ok (but blurred).
- Not looking at the camera. Looking at the camera is also acceptable, but it gives a more formal feeling.
- Black and white photo is a simple way to create consistency. In this case, all should use b/w photos and leave the colour for rollover.

We have three different approaches for this (from quickest to more complex):
1. You can send us what you have (multiple options). We choose and adjust to keep consistency.
2. You take new photos. Use a camera/lens with a good depth of field.
3. We can schedule a quick photoshoot in London.

**Comment by yalisassoon** [comment]
@bogaert - could you maybe share a folder with the different photos you took on the away week in Berlin? I think you captured most of the team then so that's a great place for us to find the first version of the photos we'll use for most of the team.

**Comment by bogaert** [comment]
Sure thing. I'll also bring my camera and tripod to the office next week to take proper portraits (like we did in New York - which is where Idan, you and I got our portraits).

**Comment by bogaert** [comment]
No need to pay for a photoshoot...

**Comment by yalisassoon** [comment]
@dangregorio any requirements on the dimensions of the photos? Any width / height ratio we should be using if we're cropping faces out of photos?

**Comment by bogaert** [comment]
> @bogaert - could you maybe share a folder with the different photos you took on the away week in Berlin? I think you captured most of the team then so that's a great place for us to find the first version of the photos we'll use for most of the team.

I didn't take portraits in Berlin so that won't work. We'll be able to photograph about half the team this week. We'll take new pictures over the coming months as people visit the office.

**Comment by bogaert** [comment]
I'm adding photos to this folder: https://drive.google.com/drive/folders/0B_Ho7UyBmOJnbG1VVmhITUoxbWM

Yali, Idan and myself are first.

**Comment by bogaert** [comment]
I photographed Giuseppe, Dilyan, Nick, and Keane. Will upload the photos later today.

**Comment by bogaert** [comment]
New photos uploaded: https://drive.google.com/drive/folders/0B_Ho7UyBmOJnbG1VVmhITUoxbWM

**Comment by yalisassoon** [comment]
Thanks @bogaert !

@dangregorio does that give you what you need? (At least to start?)

**Comment by dangregorio** [comment]
Yes.
We will update it online.
Thanks!

**Comment by jorgemgoncalves** [comment]
@yalisassoon do you want to give us an image order or should we place them randomly and you choose the sequence when placing the content?

**Comment by bogaert** [comment]
Quick update on the portraits: I'll be able to take those of Alex, Diogo, and Colm next week.

**Comment by alexanderdean** [comment]
It would be nice to be able to layout them out dynamically-randomly at some stage, like the Stripe about page:

https://stripe.com/about

**Comment by jorgemgoncalves** [comment]
@yalisassoon there are still missing the texts for each team member. Are you waiting for us to upload all the pictures?

**Comment by bogaert** [comment]
Two more photos were added (Diogo and Colm). The last one remaining needs a haircut :)

**Comment by bogaert** [comment]
Do we want to keep the pictures at 235 x 235 points? If so, I'll export the photos at twice that resolution.

**Comment by dangregorio** [comment]
Here you can see the photos ready to upload. Bigger and Black/White
https://drive.google.com/drive/u/1/folders/0BwwSh8n94UreVzJRdWlyQmd3VWs

**Comment by jorgemgoncalves** [comment]
@bogaert can you please confirm how many photos are still missing?

**Comment by bogaert** [comment]
- Leon
- Ihor
- Egor
- Anton
- Ben
- Rostyslav

Ed and Josh might provide updated pictures too. I'll take a new one for Alex next week.

**Comment by bogaert** [comment]
Forgot to add: they are all working remotely so I won't be able to take their picture right now. Instead, they'll send us a profile picture that (hopefully) meets the criteria.

**Comment by yalisassoon** [comment]
I tried adding the photos from @bogaert to the develop branch to see how they'd look - @jorgemgoncalves @dangregorio do please replace these with the updated versions you've put together.

We're working on the bios in parallel - we're not waiting for the photos to be done first @jorgemgoncalves .

Thanks!

**Comment by jorgemgoncalves** [comment]
I've uploaded the latest photos on the website. I placed @yalisassoon 's photo on the missing ones just to check if everything worked right. 

Please do me a favour, on the /img/team folder please delete all photos that aren't actual team members. 

If in the meantime you receive the missing photos inform me. Thanks

**Comment by yalisassoon** [comment]
@jorgemgoncalves - I've added initial versions of the bios. These are likely to be revised further, but should be OK to release with tomorrow.

However, we wont be able to get photos from all the team members by tomorrow. Is there an interim solution we can do (e.g. a square with the individual's initials) in the interim?

**Comment by jorgemgoncalves** [comment]
What do you think about using a simple profile picture placeholder like this one:

![profile-placeholder](https://cloud.githubusercontent.com/assets/26622929/25330455/a4b75024-28d7-11e7-9b27-3f6e9c379d0f.jpg)

**Comment by bogaert** [comment]
That's definitely better than using Yali as a placeholder 🙃

**Comment by jorgemgoncalves** [comment]
Or we can use as Yali suggested a something like this with the initials:

![profile-placeholder-v2](https://cloud.githubusercontent.com/assets/26622929/25331182/f75553a6-28d9-11e7-8161-cd7042441a1d.jpg)

What do you prefer?

**Comment by alexanderdean** [comment]
Oh that's nice! Much less anonymous

**Comment by jorgemgoncalves** [comment]
Cool! So until we receive the missing pictures I'll place these last placeholder with the missing team members' initials. Thanks @alexanderdean!

**Comment by jorgemgoncalves** [comment]
Ok, images are in place. Should we kick this issue further to milestone 1.1?

**Comment by ggaviani** [comment]
As an update to this thread, Leon and Egor have provided their photos, which I have saved in the folder below.

https://drive.google.com/drive/folders/0B_Ho7UyBmOJnbG1VVmhITUoxbWM

Egor does not have a high quality portrait photo. If the one he provided does not meet our standards, he can have another one taken.

**Comment by jorgemgoncalves** [comment]
@ggaviani these last added photos of Ben, Egor and Leon don't meet the standards. We would also like to know if the photos of Alex, Josh and Ed are final?

**Comment by bogaert** [comment]
They're final for now. We'll take proper photos at the end of June when we all meet in person again.
