### ISSUE TITLE
Some blog posts do not show the author...

### ISSUE THREAD

**Issue by ggaviani** [snowplow/snowplowanalytics.com#130]
...neither in the summarised version of the post, nor in the full post.

examples:
https://snowplowanalytics.com/blog/2017/04/03/snowplow-analytics-gets-nod-at-measurecamp-london/

https://snowplowanalytics.com/blog/2017/04/12/how-to-develop-better-games-with-level-analytics/

https://snowplowanalytics.com/blog/2017/03/30/google-cloud-dataflow-example-project-released/

**Comment by ungn** [comment]
Changes to authors.yml made in the old repo were not migrated to the new one when new joiners started contributing. Copying over all changes in old repo (and adding myself) which should fix this. Likewise with the /pages/blog/authors dir.

We probably want to do a diff between the repos at some point to ensure everything has been migrated over.
