### ISSUE TITLE
Develop a better approach for text heavy pages e.g. the blog and terms of service

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplowanalytics.com#135]
Here's a new blog post that we've just put out:

https://snowplowanalytics.com/blog/2017/04/27/snowplow-r88-angkor-wat-released/

The readability of this is really low on a 15" MBP (Firefox). It's painful having to read end to end of the blog post - the font is too large, there is too much horizontal whitespace, the code excerpts jump out a lot, bolding looks terrible, the amounts of vertical whitespace seem unpredictable.

I'll be very surprised if average dwell time on our blog posts doesn't significantly decrease until we revisit this.

**Comment by yalisassoon** [comment]
This feels like part of a larger issue with very text heavy pages e.g. the [Terms of Service](https://snowplowanalytics.com/terms-of-service/).

Renaming the ticket accordingly.

I think there are a few elements that we need to think about:

1. Font size, especially headings
2. White space around images
3. Use of width
4. Formatting of code excerpts

**Comment by yalisassoon** [comment]
Hi @jorgemgoncalves - this is out of scope of the current commissioned work - I"ll email you and Daniel on this and a number of other tickets I'd like you to quote for.

**Comment by alexanderdean** [comment]
Agree, I started noticing it on other longform pages too...

**Comment by jorgemgoncalves** [comment]
Hi guys, we have revised this issue and made some changes on the blog posts on http://next.snowplowanalytics.com. 

Can please have a look and check if readability has improved?

If so we'll apply it to other heavy text pages (privacy policy, terms and conditions, careers).

**Comment by alexanderdean** [comment]
Better! It still feels like there is a lot of whitespace *below* each heading though...

**Comment by alexanderdean** [comment]
<img width="793" alt="image" src="https://cloud.githubusercontent.com/assets/200511/26369450/9d60a092-3fec-11e7-8f1a-d242b353ada4.png">

* The bold also stands out as much much bolder than the normal text
* There needs to be a bit more vertical spacing between lines of code

**Comment by yalisassoon** [comment]
Hoping this will be solved by late next week

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon and @alexanderdean we've uploaded several changes to the most text heavy pages. Can you please check and give me your feedback?

**Comment by alexanderdean** [comment]
Can you give an example of a page @jorgemgoncalves ?

**Comment by jorgemgoncalves** [comment]
Hi @alexanderdean the css rules were applied on every blog posts in http://next.snowplowanalytics.com.

**Comment by yalisassoon** [comment]
I think it looks great! Unless @alexanderdean has spotted anything further, am closing...

**Comment by alexanderdean** [comment]
I looked at https://next.snowplowanalytics.com/blog/2017/06/12/snowplow-r89-plain-of-jars-released/

Looks good...
