### ISSUE TITLE
Make "Trusted by" box on homepage smaller

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#138]
There is a lot of white space above and below the user logos.

This means that on a normal sized monitor, you can't see any logos when you initially load the homepage, because they are below the fold.

This is unnecessary as by removing the white space you would be able to see those logos.

**Comment by jorgemgoncalves** [comment]
@yalisassoon I've removed as much white space as possible. These logos were created in a square to make it easier for them to respect the same size and position. 

Please share your thoughts.

**Comment by yalisassoon** [comment]
Looks great! Closing
