### ISSUE TITLE
Update logos on homepage

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#139]
Let's pick the most readily recognised brands:

* Nordstrom
* Economist (they needed to be added to the Trusted by page as well)
* Datadog
* Weebly
* ABC

**Comment by jorgemgoncalves** [comment]
@yalisassoon are your referring to http://www.economist.com/? The website seems to be down.

**Comment by jorgemgoncalves** [comment]
I've updated all the Trusted by on the Homepage except the Economist. Waiting for your confirmation regarding the Economist.

**Comment by yalisassoon** [comment]
The Economist is here: http://www.economist.com/. Looks like they have some website issues...

**Comment by jorgemgoncalves** [comment]
I've placed the Economist logo on the homepage and Trusted by.

**Comment by yalisassoon** [comment]
Thanks! Closing
