### ISSUE TITLE
Blog posts do not show date when shown in full

### ISSUE THREAD

**Issue by ggaviani** [snowplow/snowplowanalytics.com#142]
They do show date only when shown in summary format in the list of blog posts

**Comment by jorgemgoncalves** [comment]
This issue has been solved in [Commit ff58ef8](https://github.com/snowplow/snowplowanalytics.com/commit/ff58ef845127400b9e3776e4155229360c23a62c).

**Comment by yalisassoon** [comment]
Solved as part of new branch that will be merged shortly.

**Comment by yalisassoon** [comment]
Done - closing
