### ISSUE TITLE
Suggestion - Change white papers drop down

### ISSUE THREAD

**Issue by idanby1** [snowplow/snowplowanalytics.com#144]
In the insight page https://snowplowanalytics.com/products/snowplow-insights/
there is a drop down button for the different white papers. 

In my view, this section can easily be missed. This is important content and needs to have a more central place for easy discovery.

**Comment by yalisassoon** [comment]
@jorgemgoncalves - is there something we can do visually to make downloading the case studies a stronger call to action?

**Comment by jorgemgoncalves** [comment]
@yalisassoon I'm going to discuss this internally with Hugo and will get back to you with some solutions.

**Comment by jorgemgoncalves** [comment]
Hi, guys! We've come up with these alternatives for the drop down button:

https://drive.google.com/file/d/0BwwSh8n94UreLXFVUGZOa2FwUXM/view?usp=sharing
https://drive.google.com/file/d/0BwwSh8n94UreWk13djI3ZUVmSGc/view?usp=sharing
https://drive.google.com/file/d/0BwwSh8n94Ured0htUWJDZ3V2VTQ/view?usp=sharing
https://drive.google.com/file/d/0BwwSh8n94UreNnlqUkJPc1haSDQ/view?usp=sharing

In my opinion, we should choose the green background colour, being that we are on the Snowplow Insights page whose colour is green.

What do you think?

**Comment by yalisassoon** [comment]
Agree @jorgemgoncalves - let's go green!

**Comment by yalisassoon** [comment]
Will be done today

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon, we've completed this task and upload it to the development website.

**Comment by yalisassoon** [comment]
Looks great! Closing
