### ISSUE TITLE
Provide design of business cards and letter heads

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#155]

**Comment by yalisassoon** [comment]
Waiting on template to be setup in our Moo account and then will mark this as closed

**Comment by jorgemgoncalves** [comment]
Hey @yalisassoon we uploaded a template to Moo to test but it seems that you can't change the written information on it, so we will have to create separate templates for each team member.

We would like to know what is the card format you wish (standard, Moo, square or mini) and a list of info for each team member's card (or at least the ones that need a card).

**Comment by yalisassoon** [comment]
This should be a standard format please!

**Comment by jorgemgoncalves** [comment]
@yalisassoon are you also going to send us your team members' information?

**Comment by yalisassoon** [comment]
I thought this was being set up in my Moo account? I'll send through the details now.

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon yes this will be set up in your Moo account. The problem we encountered was that we could just upload one template and then edit the written information, so we need to upload multiple templates, one for each team member.
