### ISSUE TITLE
Serving on website from develop seems to have an issue

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#16]
The web pages don't render the way they do locally.
Looks like a CSS issue, although the CSS files themselves seem to load fine...

![image](https://cloud.githubusercontent.com/assets/201147/24325808/0e286332-1199-11e7-875a-b9b38a84296e.png)

**Comment by yalisassoon** [comment]
Could this be a caching issue? Maybe we should serve the develop site directly from s3 to save on caching issues (and caching costs?)

**Comment by jbeemster** [comment]
Hey @yalisassoon not a cache issue as max-age=0.

The hosted S3 site also has the same issue so something has gone wrong with the latest CSS...

http://next.snowplowanalytics.com.s3-website-eu-west-1.amazonaws.com/

**Comment by jbeemster** [comment]
This has been fixed and identified as a mime-type issue during the upload process.  Please re-open if any more issues like the above appear!
