### ISSUE TITLE
1.x Add Viewbix case study

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#164]
Content can be found [here](https://docs.google.com/a/snowplowanalytics.com/document/d/198T3yepTsN_WgAy4hnfuDGe5iSpf-Ztm3fLAp1ixV84/edit?usp=sharing).

Note that this has been shared with @jorgemgoncalves  - let us know if you want it shared with anyone else!

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon i've replicated Justwatch page for Viewbix. You can place the contents as you wish and afterwords we'll do our magic.

**Comment by ggaviani** [comment]
@yalisassoon , I have placed the content of the Viewbix case study page in the Develop branch. You can see it here:
https://next.snowplowanalytics.com/customers/viewbix/

Ready for Monarqa to do their magic changing images, etc.

**Comment by yalisassoon** [comment]
Thanks @ggaviani - assigning to @jorgemgoncalves to work his magic :smile:

**Comment by yalisassoon** [comment]
Hugo should have a chance to brand the page and the PDF early next week so we can put it live.

**Comment by jorgemgoncalves** [comment]
@yalisassoon @ggaviani , we are struggling to find a good photo of Dani Waxman to place next to his quote. Can you help us with this matter?

**Comment by ggaviani** [comment]
@yalisassoon , I have done a search and could only find Dani's photos on his social media profiles below, but they are the same as in our case study and fairly low resolution.

https://www.linkedin.com/in/daniwaxman/
https://twitter.com/daniwaxman?lang=en

Do you want me to ask him for a higher res photo or will you?

**Comment by jorgemgoncalves** [comment]
Hey guys, we've already upload the new images to the development website and updated the menu. 

We are still creating the PDF and waiting for a better option for Dani's picture. Give us your opinion!

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon and @ggaviani, in attachment you can take a look at the Viewbix Case Study PDF.
 
[Snowplow-Case-Study-ViewBix.pdf](https://github.com/snowplow/snowplowanalytics.com/files/1094155/Snowplow-Case-Study-ViewBix.pdf)

I've already uploaded it to the develop website assets and updated the link on the case study page. 

Take a look and give me your feedback!

**Comment by ggaviani** [comment]
Hi @jorgemgoncalves , it looks good to me. Just a couple of remarks.

1.  small typo on page 8: "This enables is customers to understand the
success of their campaigns ..." should be "This enables **its** customers to understand the
success of their campaigns ..."

2. the quote “25% of viewers who watch a video enhanced by Viewbix engage with at least
one of the apps. That’s 16 times higher than the in.” on page 11 is taken from the Viewbix website, it is not from Dani, so we might want to just put Viewbix as source rather than Dani. Same on web page. Up to @yalisassoon

**Comment by ggaviani** [comment]
@jorgemgoncalves and @yalisassoon , I also just noticed that a quote in the pdf is truncated.

Page 11: “25% of viewers who watch a video enhanced by Viewbix engage with at least
one of the apps. That’s 16 times higher than the in.”  It should be "... 16 times higher than the industry average”.

And it is taken from the Viewbix website, it is not Dani's. (I noticed the source has been changed in the web page, but not in the pdf)

**Comment by yalisassoon** [comment]
Thanks @ggaviani

**Comment by yalisassoon** [comment]
Correction has been made.

**Comment by yalisassoon** [comment]
I need to check and then mark as closed

**Comment by yalisassoon** [comment]
Looks good - can we update the image of Dani with the high res image I sent through today via email? Thanks!

**Comment by jorgemgoncalves** [comment]
@yalisassoon We've replaced Danis' image with the high res that you have sent. I believe everything is ok now.

**Comment by yalisassoon** [comment]
Thanks!
