### ISSUE TITLE
Add metadata and assets for rich previews on Linkedin and Twitter

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplowanalytics.com#166]
Last week, I linked to one of the case studies on Linkedin. This is how it was displayed:

<img width="573" alt="screen shot 2017-05-14 at 07 25 31" src="https://cloud.githubusercontent.com/assets/1975872/26032532/bcdfa92e-388d-11e7-8406-7b090f487bb4.png">

The logo is low quality with compression artifacts.

The default preview should be a high-quality logo that has both the name and hexagonal logo. How about this (screenshot from one of the design documents)?

<img width="937" alt="screen shot 2017-05-14 at 10 16 38" src="https://cloud.githubusercontent.com/assets/1975872/26032586/c9b70060-388e-11e7-8046-af72481f56cd.png">

It should also be possible to overwrite it with a page-specific asset (especially with the case studies which are rich in imagery).

**Comment by yalisassoon** [comment]
@jorgemgoncalves - any update on this ticket?

**Comment by yalisassoon** [comment]
Due to be solved at the beginning of next week.

**Comment by yalisassoon** [comment]
The suggestion is to have some new variables in the YAML front end that mean we can choose, on a page-by-page basis, what the preview image should be.

We can also use variables to set the default text.

As well as this, have a default fallback for pages where the above is not set.

It would great to know if when we're choosing images when we create new pages, what the type of image should be. (Any recommendations you have about resolution and size to make it work nicely in different environments would be great.)

**Comment by yalisassoon** [comment]
Has this functionality been delivered? It looks like it might have been - if so let me know how it works and reassign to me and I'll test.

**Comment by yalisassoon** [comment]
@jorgemgoncalves just checking in on this? I'm pretty sure this has been done and the functionality is enabled by simply adding

```
image:
```

in the YAML front end - if you can confirm and let us know how to use it, that'd be great!

**Comment by jorgemgoncalves** [comment]
Hello @yalisassoon, sorry for the delay answering.

The functionality has been created, you just need to fill in the title, description and if you wish and image just as you said. 

If none of these fields are filled you have a default meta.

**Comment by yalisassoon** [comment]
Looks great! Closing
