### ISSUE TITLE
Relative links in blog posts are off

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplowanalytics.com#167]
If I take [the factotum server blogpost](https://snowplowanalytics.com/blog/2017/04/28/introducing-factotum-server/) and click on [Why Factotum Server?](https://snowplowanalytics.com/blog/2017/04/28/introducing-factotum-server/), it scrolls a bit too far to:

![2017-05-15-12 40 21_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1737211/26056084/b137a818-396b-11e7-80c3-3844f7443e64.png)

It should display something like:

![2017-05-15-12 40 58_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1737211/26056101/c481d07e-396b-11e7-82e9-dec8118e5d60.png)

I believe this is because the height of the banner is not taken into account when offsetting the page to the proper section.

**Comment by jorgemgoncalves** [comment]
Hi @BenFradet We've checked this issue and made some changes.

Can you please confirm that it's ok now?

**Comment by BenFradet** [comment]
yup :+1: , closing
