### ISSUE TITLE
Add code highlighting

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplowanalytics.com#176]
This intersects with https://github.com/snowplow/snowplowanalytics.com/issues/135

Besides of increasing line-height we can also improve readability by adding language-specific highlighting.

Also, I think it's important to widen block itself. Most of our excerpts are in Scala and Bash, where line width used be pretty long.

![2017-05-25 1 27 47](https://cloud.githubusercontent.com/assets/681171/26419575/5a22d68e-40ea-11e7-89de-60b0b0f4d323.png)

**Comment by yalisassoon** [comment]
Hoping this will be solved by Friday next week

**Comment by jorgemgoncalves** [comment]
Hi @chuwy and @yalisassoon we've uploaded a functionality that highlights the code. Can you verify if this is working as you wish?

**Comment by yalisassoon** [comment]
I think this looks awesome! But I want to check with @chuwy and @alexanderdean as I'm not very good with colours.

Gents - what do you think of the colouring on code snippets on next.snowplowanalytics.com?

**Comment by alexanderdean** [comment]
I looked at the code on https://next.snowplowanalytics.com/blog/2017/05/24/snowplow-scala-analytics-sdk-0.2.0-released/

I think it looks lovely!

**Comment by chuwy** [comment]
Looks great! Very readable.
