### ISSUE TITLE
Validate Snowplow tag line in footer

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplowanalytics.com#18]
SNOWPLOW: DIGITAL ANALYTICS TECHNOLOGY. Is that a settled tag line? It feels a bit techie.

**Comment by alexanderdean** [comment]
Changed labels. Our tag line isn't content - it's an intrinsic part of our brand.

**Comment by yalisassoon** [comment]
I like

```
Take control of your data
```

but it's not something we've finalized...

**Comment by alexanderdean** [comment]
Shall we just remove the current line for now?

**Comment by jorgemgoncalves** [comment]
Just to close the task, the defined tagline is "Differentiate with data".
