### ISSUE TITLE
Add bigbasket.com to our users list

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplowanalytics.com#181]

**Comment by yalisassoon** [comment]
@jorgemgoncalves - is this another quick one we could knock off the list 😄 ?

**Comment by yalisassoon** [comment]
Will be done today

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon we've added BigBasket to the list of users.

**Comment by yalisassoon** [comment]
Love it! Closing
