### ISSUE TITLE
Update Snowplow logo in newsletter sign up form

### ISSUE THREAD

**Issue by ggaviani** [snowplow/snowplowanalytics.com#183]
Here is the link to it:
http://snowplowanalytics.us11.list-manage.com/subscribe?u=10bb4a6f31d5f19e0d0b54476&id=bb28c7d30d

**Comment by yalisassoon** [comment]
Agree! Can you action this please @ggaviani ?

**Comment by ggaviani** [comment]
Ok @yalisassoon , the sign up form is now updated with our new logo!

**Comment by yalisassoon** [comment]
Nice! Closing
