### ISSUE TITLE
Checkbox for Insights on request demo page

### ISSUE THREAD

**Issue by dmpacheco** [snowplow/snowplowanalytics.com#184]
There is an issue with the checkbox for Insights on the request demo page. 

The Insight checkbox is checked by default when the page is loaded. 
If a user submits the demo request, the value for insights appears as false instead of true in the demo request event. 

Expected behavior  - The value should appear as true since it was by default. The value should only be sent as false if the user unchecks the checkbox.

**Comment by yalisassoon** [comment]
@dilyand would you mind having a look at this please? No hurry...
