### ISSUE TITLE
Add social media sharing buttons to our blog posts

### ISSUE THREAD

**Issue by ggaviani** [snowplow/snowplowanalytics.com#185]
To increase sharing, promotion of our content, traffic and brand exposure beyond our followers, I would add the following sharing buttons/links to our blog posts:

Facebook
Twitter
LinkedIn
+1 by Google (Google+)

We could add more, but the above are the main ones and it is best practice to limit the number of sharing buttons shown.

Apparently native plugins are better and the best placement is considered to be at the top or on the left of the content.

Below are some blog posts about this topic for reference.
http://www.brickmarketing.com/blog/social-share-buttons.htm
https://smallbiztrends.com/2013/09/essential-social-sharing-buttons.html
http://www.gadarian.com/the-8-most-important-social-media-buttons-for-your-site/
https://coschedule.com/blog/social-media-buttons/

**Comment by yalisassoon** [comment]
Let's just put buttons for the four networks listed above

**Comment by yalisassoon** [comment]
Mock up to share early next week

**Comment by yalisassoon** [comment]
Already implemented on new branch

**Comment by yalisassoon** [comment]
It looks like this is working on next.snowplowanalytics.com but not on https://snowplowanalytics.com?

**Comment by jorgemgoncalves** [comment]
I've tested the Buttons on https://snowplowanalytics.com on Safari, Firefox and Chrome and they worked. 

Can you send us some screenshots?

**Comment by yalisassoon** [comment]
It's working for me now too - must have been a local issue... Sorry for wasting your time! Closing
