### ISSUE TITLE
Update links to Simply Business case study pdf (old format)

### ISSUE THREAD

**Issue by ggaviani** [snowplow/snowplowanalytics.com#186]
In the Simply Business blog post and in another Discourse post, there are links to the case study pdf in the old format (see links below). Let's replace it with the pdf in the new, nice layout, as on our website.

https://snowplowanalytics.com/blog/2017/01/24/how-simply-business-is-using-real-time-data-to-better-engage-and-serve-its-customers-with-Snowplow/

http://discourse.snowplowanalytics.com/t/snowplow-vs-google-analytics-and-bigquery/1122

Pdf in old format included in links above:
https://snowplowanalytics.com/assets/pdf/simply-business-case-study_v3.pdf

**Comment by yalisassoon** [comment]
Agree @ggaviani - can you make the relevant updates please?

**Comment by ggaviani** [comment]
Ok @yalisassoon , I have updated the pdf in the blog and Discourse posts.
