### ISSUE TITLE
Add case study quotes to customers page

### ISSUE THREAD

**Issue by ggaviani** [snowplow/snowplowanalytics.com#187]
@yalisassoon , I would suggest adding user quotes to our customers page in each case study teaser. I think this would make it more likely for our visitors to explore our case studies. 
https://snowplowanalytics.com/customers/

The teaser would include: a quote, photo of user (the hero), their role / job title, in addition to the user's logo and a very brief description of how they use Snowplow (logo and description are already there). There would still be 3 levels of detail for each case study (like now): teaser, case study web page and pdf.

This is similar to what Segment does, which I think works well.
https://segment.com/customers

**Comment by ggaviani** [comment]
current teaser
![screen shot 2017-06-07 at 16 34 53](https://user-images.githubusercontent.com/25175145/26888027-b2bd20a8-4ba1-11e7-9779-5b6496224c3c.png)


mock up for suggested teaser
![screen shot 2017-06-07 at 16 52 05](https://user-images.githubusercontent.com/25175145/26888074-cf1b9f86-4ba1-11e7-86a3-a882a5ee1e4d.png)

I think this would drive traffic to our case study pages / pdfs, which should help drive leads too.

**Comment by ggaviani** [comment]
I would do the same for the other case studies, using the first quote on case study web page, which is the strongest.

**Comment by yalisassoon** [comment]
@ggaviani - can you please add the quote you think we should use for each of the existing case studies? Or just confirm if it's the first quote in each case.

Assigning to @jorgemgoncalves to implement

**Comment by yalisassoon** [comment]
We can reassign to another milestone if helpful

**Comment by ggaviani** [comment]
@yalisassoon and @jorgemgoncalves , see below the quotes I would include in the case study teasers.

**JustWatch**: “Snowplow provides rich, granular data, that enabled us to build a sophisticated audience intelligence and double the efficiency of trailer advertising campaigns for our clients compared to the industry averages”, Dominik Raute, Co-Founder & CTO

**Simply Business**: "The Snowplow data set has become part of our core strategic offering", Stewart Duncan, Director of Data Science

**Peak**:  “Snowplow is really powerful when you start to hit that growth curve and going upwards: when you see the signs of accelerating growth and you need to start collecting as much event data as possible”, Thomas in’t Veld, Lead Data Scientist

**Viewbix**: “When we can show a customer that 95% of actions taken during a video happen between 0:30 and 0:35 seconds in, we have provided amazing value. The customer can in turn look at his video and learn what messaging is working, what isn’t, and make needed changes. We use analytics to show that small changes can drive significant increase in KPIs.”, Dani Waxman, Product Manager

**Comment by jorgemgoncalves** [comment]
Hey, I've been working on this request with Hugo contemplating all the if and these are our conclustions:

- Adding the photo of the customer would generate great visual noise to this block
- Some of the quotes you want to add are very long and will occupy alot of space. I've coded them so we could have an idea:

![screen shot 2017-06-21 at 11 08 53](https://user-images.githubusercontent.com/26622929/27379412-071b85d2-5673-11e7-8545-87219b0c47aa.png)

Is it possible for you to review the quotes and keep them with a maximum of 180 characters or would it deprecate the original quote to much?

**Comment by yalisassoon** [comment]
I will review and put together some shortened quotes. Let's see if they work

**Comment by yalisassoon** [comment]
Do the following shortened quotes work @jorgemgoncalves ?

Simply Business: "The Snowplow data set has become part of our core strategic offering", Stewart Duncan, Director of Data Science

JustWatch: “Snowplow enabled us to build a sophisticated audience intelligence and double the efficiency of campaigns”, Dominik Raute, Co-Founder & CTO

Peak: “Snowplow is really powerful when you start to hit that growth curve and going upwards”, Thomas in’t Veld, Lead Data Scientist

Viewbix: “When we can show a customer that 95% of actions taken during a video happen between 0:30 and 0:35 seconds in, we have provided amazing value.”, Dani Waxman, Product Manager

If not let's close this issue...


Yali

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon and @ggaviani, I've uploaded the changes on the customers' page on the development website. 

Please give me your feedback.

**Comment by yalisassoon** [comment]
Looks great @jorgemgoncalves ! Only update I'd like to make is the text size for "Dani Waxman" looks too big? (Larger than the other authors?)

**Comment by jorgemgoncalves** [comment]
You were absolutely right! I've already corrected it.

**Comment by yalisassoon** [comment]
Looks great! Closing
