### ISSUE TITLE
Add "where did you first hear about us" question in Contact us and Demo forms

### ISSUE THREAD

**Issue by ggaviani** [snowplow/snowplowanalytics.com#188]
@yalisassoon , I would add the question "where did you first hear about us" in our Contact us and Demo forms to help us gauge the impact of our marketing activities. Especially for the offline activities that are not as easy to track.

I would make this field optional to prioritise having the form completed vs having this extra information and suggest the following list for the drop down menu (I have deliberately kept the list short to keep it simple for visitors). 

Event e.g. Meetup
Social media
Blog
Search
Other (please specify)

**Comment by yalisassoon** [comment]
Not going to do this either
