### ISSUE TITLE
Call our case studies "success story" or "user story"

### ISSUE THREAD

**Issue by ggaviani** [snowplow/snowplowanalytics.com#189]
On our website and pdf. Same meaning, but it evokes something more interesting to read.

**Comment by ggaviani** [comment]
![screen shot 2017-06-07 at 16 34 53](https://user-images.githubusercontent.com/25175145/26888027-b2bd20a8-4ba1-11e7-9779-5b6496224c3c.png)

**Comment by yalisassoon** [comment]
Not going to do this - unknown upside for potentially big SEO downside...
