### ISSUE TITLE
Add Picnic.nl case study

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#191]
@ggaviani - can you please post here two links:

1. To the full case study text
2. To the shortened version of the text?

We can then assign to the Monarqa team to brand.

Thanks

**Comment by ggaviani** [comment]
@yalisassoon , Here are the links to the Picnic case study:

full case study: https://drive.google.com/open?id=1jKhahq4tsM5_diZaa-Pu9k2wA2_PIEfTGF8ZpH6NRic

copy for web page: https://drive.google.com/open?id=1f-rHDNeQhqO5S1IJMa_yemvOTiwASo22rwOC8Ab8P8U
 
I have chased Picnic today to get their sign off, but they are still reviewing the case study.
So maybe better to wait for their sign off before assigning it to Monarqa, as if they want us to make changes, Monarqa may have to re-do the branded layout.

**Comment by yalisassoon** [comment]
Understood - I'll reassign back to you and you can let me know once we get that feedback through.

**Comment by yalisassoon** [comment]
We've had the green light from the Picnic team to publish it.

Monarqa team - latest version of the case study can be found here: https://docs.google.com/document/d/1jKhahq4tsM5_diZaa-Pu9k2wA2_PIEfTGF8ZpH6NRic/edit?usp=sharing.

Thanks!

**Comment by yalisassoon** [comment]
Going to mockup/  do white papers mid next week.

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon, we are almost finished creating PicNic's case study page although it seems that this page is a lot more extensive than the other case studies.

Please take a look at this [mockup](https://drive.google.com/open?id=0B_-rK3P8F8xVRXFDdmQ4Tk1Hb0U) (still with no images) to understand what we mean. 

Is it possible to shorten the content so that it takes up less vertical space?

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon, 

[Here](https://drive.google.com/open?id=0B09pW_o37q9-bTZKdHhkS0hmdzA) you can see the mockup of the full case study.

I've noticed at the beginning of the issue that there is a short version for the website but I haven't access to it, can you please send it so we can update the page?

**Comment by yalisassoon** [comment]
Hi @jorgemgoncalves - the case study looks great! I've reshared the shorter version of the website.

> Is it possible to shorten the content so that it takes up less vertical space?

Do you mean we should shorten the [website version](https://docs.google.com/document/d/1f-rHDNeQhqO5S1IJMa_yemvOTiwASo22rwOC8Ab8P8U/edit) or the [full PDF](https://drive.google.com/file/d/0B09pW_o37q9-bTZKdHhkS0hmdzA/view)?

**Comment by jorgemgoncalves** [comment]
@yalisassoon I thought you only had the full PDF document and I was asking to shorten the document for the website version but it's all sorted now that I've read the hole issue 😓

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon,

[Here](https://drive.google.com/open?id=0B09pW_o37q9-b2x2eFIxQjNLdkE) you can see the updated mockup of the case study page! 

Please give me your feedback in order to start implementing it.

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon, we've published the news PicNic case study on the https://qa.snowplowanalytics.com. 

We've changed the menu, footer, customer's page and created the news page with the PDF download.

Please share your thoughts.

**Comment by yalisassoon** [comment]
Hi @jorgemgoncalves - this looks good - the only outstanding issue I've spotted is that you've capitalised the "n" in picnic in the menus i.e. "PicNic" not "Picnic". I think that's a mistake? 

Can you please update the mnrq-191-picnic-case-study branch accordingly and then issue a pull request into next.snowplowanalytics.com when done?

**Comment by jorgemgoncalves** [comment]
Hey @yalisassoon, I've corrected the PicNic N and created a pull request to next.snowplowanalytics.com.

**Comment by jorgemgoncalves** [comment]
After #280 the Picnic case study was successfully added to the production website.
