### ISSUE TITLE
Put together CSS for greenhouse.io jobs section our website

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#196]

**Comment by yalisassoon** [comment]
https://app.greenhouse.io/configure/dev_center/css_guide

**Comment by yalisassoon** [comment]
Hi @jorgemgoncalves - you can view the careers homepage here: https://snowplowanalytics.com/company/careers/ and an example job listing here: https://snowplowanalytics.com/company/careers/?gh_jid=700719.

I think the main things we want to accomplish are:

1. Make the job listings look like part of the site. (I.e. make the font and colourings consistent.)
2. Ensure that the form that candidates submit still looks good / is functional. (This broke when I tried adding the existing snowplow.css directly.) 
3. Make sure that the listing is readable.

We can revise this at a later date - at this stage it's just about making the listings reasonably attractive.

**Comment by yalisassoon** [comment]
Let me know if you need access to greenhouse admin panel. (This is where you can add your own css location.)

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon can you please give us access to Greenhouse admin panel?

**Comment by dangregorio** [comment]
This week we are doing the new skin process. We are developing and testing it live making all iterations visible. Users will notice all the steps of the development, but it will be much easier and quicker. Off course, we try to schedule each update to maintain the consistency of the layout throughout all process.
When the process is done, we'll ask for your feedback.

**Comment by jorgemgoncalves** [comment]
@yalisassoon if you visit the Careers page, you will see that:

- there's no longer a huge space between the title and the job listing and that these elements are inside a light blue box giving it a better look.
- Inside the each Job we've hidden the title replication and we also corrected the problem with the CV upload.

Meanwhile, we discovered a bug with the iframe that each time some submits an application the height of the page increases.

**Comment by yalisassoon** [comment]
This is done except fixing a bug on Safari where the job listing is split across two columns:

![image](https://user-images.githubusercontent.com/201147/28668773-63763e22-72c9-11e7-95f6-65c8fa06a5e1.png)

**Comment by yalisassoon** [comment]
Looks like this bug is still here

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon we've corrected this bug and now it correctly separates each job among the columns.
