### ISSUE TITLE
Fix top level menu underlining of currently active page

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#2]
Doesn't work currently

**Comment by petermonte** [comment]
For some reason the printing is not happening in [menuClassActive.fn](snowplowanalytics.com/_includes/fn/menuClassActive.fn).

The folder `fn` under `_includes` holds includable files with script logic. It's a way to avoid really dense logic on simple markup making it difficult to understand front-end.
