### ISSUE TITLE
Setup redirects from some of the old web page that wont be in the new website to new pages in Discourse

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#20]
Hi Josh,

One section of the website that we'll be deprecating in the move is the documentation section:

1. Some of this will move to Discourse
2. Some of this will be junked
3. We'll then launch a new contentful powered documentation section specifically geared around Snowplow Insights and Snowplow React users

For (1) I'll want migrate the content onto Discourse and then I'll want to setup redirects from the current location to the new location. Do you know how I should do this? What's the best way to manage it? (It might end up being quite a long list of redirects.)

**Comment by jorgemgoncalves** [comment]
heads-up: several blog posts also have links that need to be redirected.

**Comment by jbeemster** [comment]
We need to add routing rules to the hosting S3 Bucket of the form:

```
<RoutingRules>
  <RoutingRule>
  <Condition>
    <KeyPrefixEquals>redirect/key/here</KeyPrefixEquals>
  </Condition>
  <Redirect>
    <HostName>discourse.snowplowanalytics.com</HostName>
    <ReplaceKeyWith>new/host/key</ReplaceKeyWith>
  </Redirect>
  </RoutingRule>
</RoutingRules>
```

If you can get me a list of everything that needs to be redirected I can upload the ruleset.

**Comment by yalisassoon** [comment]
Adding @ggaviani to this card - @ggaviani we'll work on this together tomorrow. (I'll brief you in the morning.)

Thanks

**Comment by yalisassoon** [comment]
Reassigning back to @jbeemster (sorry / thanks!)

Please can we setup the following redirects:
| **FROM** | **TO** |
|:-----------|---------|
| http://snowplowanalytics.com/guides/recipes/customer-analytics/cohort-analysis.html | http://discourse.snowplowanalytics.com/t/performing-cohort-analyses-with-snowplow/1154 | 
|  http://snowplowanalytics.com/guides/recipes/platform-analytics/funnel-analysis.html    | http://discourse.snowplowanalytics.com/t/funnel-analysis/1152 |   
| http://snowplowanalytics.com/guides/concepts/sending-data-into-snowplow/ | http://discourse.snowplowanalytics.com/t/sending-data-into-snowplow/1151 |
| http://snowplowanalytics.com/guides/recipes/catalog-analytics/market-basket-analysis-identifying-products-that-sell-well-together.html | http://discourse.snowplowanalytics.com/t/market-basket-analysis-identifying-products-and-content-that-go-well-together/1132 |

**Comment by yalisassoon** [comment]
I need to add a few more - just need to jump into a meeting

**Comment by jbeemster** [comment]
First set is done

**Comment by yalisassoon** [comment]
Thanks @jbeemster - I think the list is complete now!

**Comment by jbeemster** [comment]
All added!
