### ISSUE TITLE
Put together initial mockup of partners section 

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#203]
Based on the mockup I emailed Daniel on June 29th.

**Comment by yalisassoon** [comment]
Hopefully have something middle of next week.

**Comment by yalisassoon** [comment]
Hopefully receive August 1st for some initial mockups

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon as promised here are the new mockups for the new partner section. We feel that are still a few things to be improved but wanted to receive your feedback before moving on. 

You can see the mockups [here](https://drive.google.com/open?id=0B24yFNN5aMhmU2hpQ3pnWndTbU0).

Please give us your thoughts.

**Comment by yalisassoon** [comment]
This looks great @jorgemgoncalves - I will come back with some content and ask you to slot it in / make a few updates. We can then share the first version of this with our partners.

**Comment by yalisassoon** [comment]
HI @jorgemgoncalves - please find an updated version of the text content for the pages [here](https://docs.google.com/a/snowplowanalytics.com/document/d/1QhdK1_zPKMlZIGgC7K6ZlH0gthFQlAxDfTdARELMtm0/edit?usp=sharing). Let me know if you have any questions - otherwise hoping you have enough to create a new branch and add the pages their?
