### ISSUE TITLE
Bug with CSS on jobs page

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#211]
When someone uploads their CV on any of the jobs pages, the "LinkedIn Profile", "Website" and "How did you hear about this job? " and "Submit Application" button are hidden.

Can you please look into this as a priority?

Thanks!

**Comment by yalisassoon** [comment]
Should be solved today

**Comment by jorgemgoncalves** [comment]
@yalisassoon, the CV upload no longer creates a massive image that pushed the content down. The only issue that we found is regarding a javascript that increases the height of the content every time you press the submit button.
