### ISSUE TITLE
Add title, description and image meta tags for each page

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#215]
Let's prioritise the main pages (i.e. not every blog post).
I'll work with the team publishing blog posts so we start to include these ourselves with new content that we write.

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon, please check this link to see our [Metadata](https://docs.google.com/spreadsheets/d/1IAHx8n3J9vFZLnL-HWGvNWDSAjcGJlDKi77h8yxKhE4/edit?usp=sharing) suggestions for titles and description. 

Give me your feedback so that I can start uploading them to the website.

**Comment by yalisassoon** [comment]
Looks good! Can we put this live please @jorgemgoncalves

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon i've placed the meta online on the new branch develop-new-blog-travis.
