### ISSUE TITLE
Excerpts do not respect more tag

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplowanalytics.com#219]
I thought I had logged this one but apparently not.

On the previous website, the excerpt visible for each blog post on https://snowplowanalytics.com/blog/ was delimited by a `<!--more-->` tag which doesn't seem to be the case anymore as the excerpt seems to be cut off at some arbitrary number of characters which defeats the purpose of an excerpt altogether.

**Comment by yalisassoon** [comment]
@BenFradet we don't intend to fix this - it's part of the redesign to make the blog roll more readable. We cut each post after 75 words.
