### ISSUE TITLE
Fix logo in Discourse Summary emails

### ISSUE THREAD

**Issue by ungn** [snowplow/snowplowanalytics.com#227]
Fixing the logo on Discourse (https://github.com/snowplow/snowplowanalytics.com/issues/120) seems to have made the logo in the Discourse summary email illegible due to the white background in the email and image transparency of the PNG file (and the white text of the logo itself).

This assumes that the same file is being used for both the emails and the Discourse forum. Simple fix would be to use a non-transparent logo for the emails, but there may be other options available.

**Comment by yalisassoon** [comment]
@jorgemgoncalves is going to see if we can have separate logos for the emails and the website

**Comment by jorgemgoncalves** [comment]
I've followed @dilyand approach and uploaded the logo onto the [Assets for the site design](https://discourse.snowplowanalytics.com/t/assets-for-the-site-design/7) topic and used that link to place replace the Digest Logo on the emails. 

Let us wait and see if this works.

**Comment by ungn** [comment]
LGTM! New black text logo is appearing in the summary emails.

Closing as complete.
