### ISSUE TITLE
Update team photos

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#234]
We need to add entries for:

* Mike
* Sarah
* Nicki
* Tim

Remove entries for:

* Idan
* Giuseppe

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon, I've removed Idan and Giuseppe from the team grid. 

Can you give me the new collaborators first and last name so that I create their placeholder with their initial while we don't have their photos?

**Comment by bogaert** [comment]
@yalisassoon I'll bring my camera to work and take pictures.

**Comment by yalisassoon** [comment]
Hi @jorgemgoncalves - the new team members to add are:

* Mike Nemirovsky
* Nicki Iodice
* Tim Haines

Thanks!

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon, I've added the new team member to a new branch with placeholders and the bio sent by Nicki, Mike and Tim.

I've and already asked for a merge with next.snowplowanalytics.com on #308

**Comment by jorgemgoncalves** [comment]
@yalisassoon tested the new member on next.snowplowanalytics.com and everything is working correctly.

Created a new pull request to merge this commit with master #314.

**Comment by bogaert** [comment]
My camera is broken so I won't be able to take new profile pictures.
