### ISSUE TITLE
Update team photos for those that are missing

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#235]
These were taken on the away week

**Comment by bogaert** [comment]
New pictures uploaded for Anton, Alex, Ben, Leon, Josh: https://drive.google.com/drive/folders/0B_Ho7UyBmOJnbG1VVmhITUoxbWM

**Comment by jorgemgoncalves** [comment]
I've updated the latest team photos. At this point we are missing only new photos for Ed and Ihor.
