### ISSUE TITLE
Where has the new Snowplow color palette been defined?

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplowanalytics.com#24]
The signature color in our new brand seems to be the purple #5b0098. There's also a green (closely associated with Snowplow Insights) and a blue (closely associated with Snowplow React). Can you clarify the full new colour scheme for Snowplow? It's unclear to me.

**Comment by dangregorio** [comment]
Attached the current Snowplow palette. If needed, we can provide the colour codes.

![snowplow_brand_v6_colours](https://cloud.githubusercontent.com/assets/26771127/24810681/1296aeb6-1bbb-11e7-9e23-c12d29443488.jpg)

**Comment by alexanderdean** [comment]
Thanks

**Comment by yalisassoon** [comment]
Discussion has moved on since this ticket was raised - closing
