### ISSUE TITLE
URGENT: Blog links don't work in new version of jekyll

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#242]
HI @jorgemgoncalves @petermonte 

There's an issue with the new version of Jekyll - the blog post URL paths aren't working. I don't understand how I didn't spot this when testing (suspect it was a caching issue) but...

1. If you go to https://next.snowplowanalytics.com/blog/
2. If you click on any of the blog post links they 404 e.g. https://next.snowplowanalytics.com/blog/2017/07/21/elasticsearch-loader-0.9.0-released
3. If you add a `.html` to the post title it does work e.g. https://next.snowplowanalytics.com/blog/2017/07/21/elasticsearch-loader-0.9.0-released.html

Please can we get this fixed as our first priority? We've reverted the merge from develop to master so hopefully the broken links on the site should be fixed in the next hour. (It is currently being deployed.)

Speaking to @jbeemster he thinks it might be a bug in the version of Jekyll-paginate that we're using, and that updating to the latest version should fix it.

Thanks,

Yali

**Comment by yalisassoon** [comment]
It looks like this issue doesn't occur when building locally, only on next.snowplowanalytics.com or https://snowplowanalytics.com

cc @jbeemster

**Comment by yalisassoon** [comment]
So @petermonte @jbeemster...

It looks like this is an issue deploying the website via s3 / cloudfront. It looks like there are two approaches to getting the post URLs to not include the `.html` extension as per [this post](https://simpleit.rocks/having-pretty-urls-in-a-jekyll-website-hosted-in-amazon-s3/):

1. Change the structure of the posts in the repo from `/_posts/yyyy-mm-dd-my-post-name.md` to /_posts/yyyy-mm-dd-my-post-name/index.html`. This is what we were going to do originally but had the issue that the post URL was `/yyyy/mm/dd/my-post-name-index`. We couldn't have the `-index` at the end because it would have meant all previous links to the post would 404. Potentially though we could fix that?
2. Have a script that runs as part of the deploy, that renames all our `.html` files that are not `index.html` to remove the extension prior to deploying to s3.

1 would be a job for @petermonte, 2 would be a job for @jbeemster.

My preference would be to go with (1) if it isn't too tricky. @petermonte what do you think? Can we get to the bottom of the `-index` issue?

**Comment by petermonte** [comment]
@yalisassoon your point **1** assumes that we are going back to the folder structure with a ìndex.html` file inside. Is this correct? Because my last commit was to go back to the simple `****.md` file with no need of folder.

**Comment by yalisassoon** [comment]
HI @petermonte - my understanding based on the blog posts is that if we go back to a folder structure with a `index.html` this will solve the problem. As it is: the current setup will have the correct URLs when building locally, but the incorrect URLs when serving from S3 / Cloudfront _unless_ we implement fix (2).

My issue with fix (1) was that when we had the posts in that structure there was an `-index` in the page path which we didn't want. So if we could move back to that folder structure, but fix the issue with the path to remove the `-index`, that would be my preference.

Does that make sense? Happy to jump on a call to discuss...

**Comment by petermonte** [comment]
@yalisassoon It makes sense to me too.

My concern with that approach is that it requires me to come up with a solution for the paths. Now this is an issue that I'm honestly struggling to understand how to overcome it. My knowledge of Jekyll or even Ruby isn't that much. And let's face it, Jekyll documentation isn't the best. Most of what you learn isn't from the docs page but from issue on github :(

So yes, I'll implement again the folder structure but will require some time to do some research. In this situation any help is really welcome : )

**Comment by yalisassoon** [comment]
Understood Peter. If you can update a couple of the blog posts to the new structure and merge to develop, I can then have a look and see if I can help figure out how to fix it.

Things we could try:

1. If we update to the structure do we still have the `-index` in the path?
2. Does the path end in `.html` on next.snowplowanalytics.com? Or is that issue at least resolved?
3. What happens if we add a permalink to the post front end? Does that solve the issue

I'm optimistic we can either solve it pretty soon, or if none of those things work ask @jbeemster to update our deploy script to remove the `.html` extension on the posts. But first let's experiment with 2 or 3 posts to see if we can get them working on next.snowplowanalytics.com.

**Comment by yalisassoon** [comment]
@petermonte please can you update the oflder structure for each post so that it is as per https://github.com/snowplow/snowplowanalytics.com/tree/develop/_posts/2017-07-21-elasticsearch-loader-0.9.0-released.

Note that I think each post can be `index.md` rather than `index.html` but otherwise as it was before we reverted to the original structure.

Any issues please let m eknow - I'd love to get this sorted today so we can get on with all the more exciting stuff we want to do on the website.

**Comment by petermonte** [comment]
@yalisassoon changed folder structure and got links working correctly locally. Sorry for the amount of files but thought that backing up old structure would be wise and simple even if in repo.

**Comment by yalisassoon** [comment]
Hey @petermonte - just tried building the site locally after fetching the updated `develop` branch and I'm getting the following error:

```
$ bundle exec jekyll serve --host 0.0.0.0
Could not find jekyll-paginate-v2-1.8.1 in any of the sources
Run `bundle install` to install missing gems.
```

Isn't the only update the folder structure for the posts? Why are the gem dependencies changed?

**Comment by yalisassoon** [comment]
Currently not building:

```
$ bundle exec jekyll serve --host 0.0.0.0
Configuration file: /vagrant/_config.yml
            Source: /vagrant
       Destination: /vagrant/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Complete, processed 1 pagination page(s)
  Liquid Exception: Liquid syntax error (line 179): Unknown tag 'endmarkdown' in /vagrant/_posts/2013-08-12-towards-universal-event-analytics-building-an-event-grammar/index.html
jekyll 3.5.0 | Error:  Liquid syntax error (line 179): Unknown tag 'endmarkdown'
```

**Comment by yalisassoon** [comment]
Hey @petermonte 

This is a bit frustrating:

1. The site isn't building locally for me. The issue is that multiple blog posts are missing the opening `{% markdown %}` tag. I've fixed this in some posts: https://github.com/snowplow/snowplowanalytics.com/commit/9612aa843ed5a82636778353debb34b08eeeab84 - but I'm a bit loathe to go through every one of them just to test your update. It makes me suspect you either haven't tested the branch locally, or you haven't committed the latest version to Origin.
2. I included an example of the new structure in my update: https://github.com/snowplow/snowplowanalytics.com/tree/develop/_posts/2017-07-21-elasticsearch-loader-0.9.0-released. Note that the post extension is `md` rather than `html`. This should mean that the markdown liquid tags are not required. I'm happy to have the extension be `.html`, but if that means that the code highlighting in the blog posts is broken, then we need update the extensions to `.md` as per my example to get that issue resolved.
3. Once the updates are made I'd like to see the changes merged to the `develop` branch so we can test them on next.snowplowanalytics.com. I'd like part of the testing you do to be to see that the updates work on next.snowplowanalytics.com please.

Thanks,


Yali

**Comment by petermonte** [comment]
I @yalisassoon,

I understand your frustration, and for that I am the one to blame.

Since the beginning of this task that I was led to assume, under the documentation and issues of `jekyll-paginate-v2`, that posts structure would have to be under a folder holding an `index.html` file. But today, I realised that we don't need any structure of folders or `indexes` or `*.md` inside folders. It might be because of new updates of either the plugin or Jekyll in relation to the documentation date that stated such restriction.

On the latest commit I left `_posts` folder has it was, without any folder structure. As result, paginating seems to work fine and links no longer have any issue.

**That goes without saying that it is required for you to test it locally and remotely.**

I'm adding this video with a screen [recording](https://dl.dropboxusercontent.com/u/1923549/snowplow-test-2.gif) so that you can see my local tests.

**Comment by yalisassoon** [comment]
Hi @petermonte 

Many thanks for working on this over the weekend.

I'm not interested in blame / fault. I just want to get it sorted quickly.

We aren't communicating effectively on this thread at all. What I see in the latest commits is not what I want or what I thought I asked for.

Please can we jump on a quick Skype call to discuss? I've requested this from @jorgemgoncalves (sorry I don't have your email)...

Thanks


Yali

**Comment by petermonte** [comment]
@yalisassoon yes we can.

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon,

At this point, we've already added the permalink to all the blog posts.

We've been checking the #anchor issue, and we verified that you are writing them with postsname#id and I believe they were written this way because you also use them on the old Excerpts that showed on the Post Feed.

We have two ways of solving this issue:

- We change all the links on the posts deleting all the information before the #,  but this would change every link with # on the posts.

- We can assign a class to anchors inside <ol> (these links only show inside ordered lists right?) so that you can continue writing URL with postsname#id and this way the link works as a hyperlink with an anchor on the Post Feed and only as an anchor inside the post. 

Which do you believe will be the best option?
