### ISSUE TITLE
Can we add a margin / padding on the careers page

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#244]
https://github.com/snowplow/snowplowanalytics.com/tree/develop/_posts/2017-07-21-elasticsearch-loader-0.9.0-released
![image](https://user-images.githubusercontent.com/201147/29212800-4248a610-7e98-11e7-8db8-0c4d89859f73.png)

On the hero image there's no padding on the left or the right (see above)

**Comment by yalisassoon** [comment]
Do you think we shoudl have a margin on the side of "Join the Snowplow Team..."?

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon, I've placed the headings inside a container that has standard margins and paddings.
