### ISSUE TITLE
"Know More" links for commercial and OSS products on product page don't go anywhere

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplowanalytics.com#27]
http://next.snowplowanalytics.com/products/#

**Comment by jorgemgoncalves** [comment]
@yalisassoon each OpenSource product will have and individual page? If not where should the "Know More" buttons link to?

**Comment by yalisassoon** [comment]
The "Know More" buttons should point to the Github repos:

* https://github.com/snowplow/snowplow
* https://github.com/snowplow/iglu
* https://github.com/snowplow/sauna

**Comment by bogaert** [comment]
This should be Learn More no?

**Comment by yalisassoon** [comment]
Already is @bogaert
