### ISSUE TITLE
New favicon is hard to see

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplowanalytics.com#29]
Low contrast, very thin:

<img width="1300" alt="favicon" src="https://cloud.githubusercontent.com/assets/200511/24551351/062b6e1a-161a-11e7-9382-95d6420e241a.png">

<img width="1007" alt="favicon2" src="https://cloud.githubusercontent.com/assets/200511/24551407/36b60504-161a-11e7-8107-922050a4b834.png">

**Comment by jorgemgoncalves** [comment]
We've updated the favicon. Please share your thoughts

**Comment by alexanderdean** [comment]
Love it!

**Comment by jorgemgoncalves** [comment]
Great! Thanks for the feedback.
