### ISSUE TITLE
Create cross content sections to improve navigation

### ISSUE THREAD

**Issue by jorgemgoncalves** [snowplow/snowplowanalytics.com#292]

**Comment by yalisassoon** [comment]
@jorgemgoncalves idea: more blocks in each page funneling people to contact us, request a demo.

Design will be very similar to the design used for the CTAs on the blog post

**Comment by yalisassoon** [comment]
Currently focus is on those CTAs. Will revisit later if there's extra we want to do here.

**Comment by yalisassoon** [comment]
@Mandelliant going to do some brainstorming around if there are some easy connections we can make that we're failing to do at the moment.

**Comment by jorgemgoncalves** [comment]
Hi @Mandelliant, going to assign this issues to you since we've already pushed the CTA's into next.snowplowanalytics.com. 

If you require further assistance from up please assign it back to me.

**Comment by yalisassoon** [comment]
Merged with visual calls to action and delivered.
