### ISSUE TITLE
Update our Discourse template so that we drive more users back to the main website

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#298]
Currently once you arrive at the Discourse, it's back to the website unless you click a specific page link.

Let's think about driving more people back by:

* Making the discourse more a "part" of the website (e.g. with the top menu nav)
* Including more cross sectino calls to action in discourse (if possible)
* Maybe have an "ad unit" that we put somehwere on the side

These are just random ideas - looking to @jorgemgoncalves  anq team Monarqa team to tell us what they think would work best (and then implement).

**Comment by yalisassoon** [comment]
iFrame approach doesn't really work so going to update the Discourse tempate so that it uses the same menu as on the main Snowplow website

**Comment by yalisassoon** [comment]
Current approach looks good - can we fix this:

![image](https://user-images.githubusercontent.com/201147/33430778-a76b09f6-d5c9-11e7-99d6-c22e791ddd97.png)

We're not too concerned about showing the menu in a mobile environment.

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon, sorry for the late feedback. I've already fixed this issue. Can you please confirm?
