### ISSUE TITLE
Make partner a top level menu item

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#3]

**Comment by petermonte** [comment]
We need to consider the length of the menu. Right now the number of items are compromising the bootstrap responsive behaviour. So adding another item will require some css to get things working correctly.

**Comment by petermonte** [comment]
This change rases another point: Is Partners still a sub-page of Company? If so, and while living in a separated menu item, should Company menu have a sub-page Partners too?

**Comment by alexanderdean** [comment]
This has been done already, changing milestone
