### ISSUE TITLE
Decide how much pricing information we include on the website

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplowanalytics.com#30]
There's no information about the cost of our products in any currency. Is that deliberate?

**Comment by jorgemgoncalves** [comment]
@yalisassoon should we include the current price table in the "Request a Demo" page?

**Comment by yalisassoon** [comment]
I think we should indicate pricing on the product pages only. (I.e. only on the Snowplow Insights page.)

**Comment by jorgemgoncalves** [comment]
@yalisassoon as discussed in yesterdays' skype (11/04) the pricing won't be placed on the website for now. Should this issue be placed in another milestone?

**Comment by yalisassoon** [comment]
Yes - I'll rename it and put it out to another milestone - thanks @jorgemgoncalves

**Comment by alexanderdean** [comment]
This has been done, closing.
