### ISSUE TITLE
Implement partner page as per design / content

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#300]

**Comment by yalisassoon** [comment]
Aim to launch at the end of this week and we might make revisions. @jorgemgoncalves to send an update on Wednesday.

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon, I've finished merging the new Partners section onto qa.snowplowanalytics.com.
Can you please take a look and give me feedback before we merge it to next and then to master?

**Comment by yalisassoon** [comment]
Hi @jorgemgoncalves - the new pages look great! There's quite a lot of smaller bits and pieces that need to be completed before we can push these lives though:

* The Technology Partners Page isn't loading? Is it missing?
* The company logos don't link through to the company web pages
* Can we add the following logos to our Technology Partners section:
  * https://predicsis.ai/
  * chartio.com
  * Mode https://modeanalytics.com/
  * Periscope https://www.periscopedata.com/
  * Parrable https://www.parrable.com/
  * Augur https://www.augur.io/
  * More to come but let's start with these...
* On the implementation partners section can we remove any quotation marks from the company bylines?
* Can we make sure client logos link through to those clients?

Thanks!

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon, all done! Please confirm in qa.

**Comment by yalisassoon** [comment]
Looks good @jorgemgoncalves ! Only two updates I think we need to make:

On the main partner page one of the logos doesn't seem to be loading:

![image](https://user-images.githubusercontent.com/201147/31703722-c5a95000-b3d5-11e7-95f2-bbeeb691aa61.png)

When we list "Key2Market" on the Implementation Partner section, can we list their location as "Berlin" rather than "Germany"? (To make them consistent with Leroi?)

Once that's done I think we're good to go - please make a PR into next.snowplowanalytics.com.

**Comment by jorgemgoncalves** [comment]
@yalisassoon as promissed i've created a pull request to merge the Partners Section into next.snowplowanalytics.com #346 and assigned it to you.
