### ISSUE TITLE
1.9 Skin our Meetups pages

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#301]

**Comment by yalisassoon** [comment]
@jorgemgoncalves don't forget to join our meetup groups and then ping me - I can give you permission to update them.

The top priority page is our Berlin one - having a meetup there in a few weeks...

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon, we've completed skinning all Meetups pages. Closing the issue.
