### ISSUE TITLE
Create users page

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#32]
This would include a long list of logos of all our different users. (Similar to [this](http://snowplowanalytics.com/product/users/).)

**Comment by jorgemgoncalves** [comment]
@yalisassoon Threw out the website we now have Customers, Trusted By and Users. We should stick to only one reference.

Where is this page present in the navigation?
- Top  menu: inside Customers?
- Footer: under Customers?

**Comment by yalisassoon** [comment]
Maybe a submenu in the Customers menu called "Overview"?

**Comment by dangregorio** [comment]
Isn't the [Customers page](https://next.snowplowanalytics.com/customers/) the overview of this section?  
Wouldn't "Trusted by" be more appropriate?
It would also be more aligned to what is used in the Company page (Trusted by grid).
This way we could also rename this page to snowplowanalytics.com/trustedby

**Comment by yalisassoon** [comment]
> Isn't the [Customers page](https://next.snowplowanalytics.com/customers/) the overview of this section?

Yes it is!

> Wouldn't "Trusted by" be more appropriate?

Happy to go with "Trusted by". Just so long as the menu title is "Customers"

Does that answer your questions?

**Comment by dangregorio** [comment]
Yes. Thanks!
In that the case we'll do the following:
- Change the name of  "Users" page to "Trusted By", including the url /trustedby
- Add the "Trusted by" item under "Customers"

**Comment by yalisassoon** [comment]
Great!

**Comment by jorgemgoncalves** [comment]
The "Trusted By" page has already been created and is available at: http://next.snowplowanalytics.com/customers/trusted-by/
