### ISSUE TITLE
Issue with footer on next.snowplowanalytics.com but not on local copy

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#35]
On my local copy the footer renders nicely:

![image](https://cloud.githubusercontent.com/assets/201147/24654475/6e027166-1942-11e7-84a9-aa53c90c06ef.png)

But on next.snowplowanalytics.com it doesn't:

![image](https://cloud.githubusercontent.com/assets/201147/24654492/8000d772-1942-11e7-9c64-981f480c1e26.png)

@jbeemster do you have any idea what's going on? Might it be another mime-file type issue?

**Comment by jbeemster** [comment]
This seems to be an odd caching issue.  In an incognito browser I do not see this issue but in my normal browser it is showing the same as you.

I will force a CloudFront refresh and see if that fixes it.

**Comment by jbeemster** [comment]
Fixed - old optimizely experiment for integration testing of the JS Tracker was at play.
