### ISSUE TITLE
Add GTM container to website

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#38]
So we can enable Snowplow JS tracker!

**Comment by yalisassoon** [comment]
@bogaert should this be the same container tag as we use on the current website? Or should we start fresh?

**Comment by bogaert** [comment]
Depends on the timeline. I have a meeting with @dilyan on Monday to rethink our tracker setup.

**Comment by bogaert** [comment]
@dilyand will start work on this tomorrow. Could you set up the container for him, @yalisassoon?

**Comment by bogaert** [comment]
New container created, called `next.snowplowanalytics.com `. Closing.
