### ISSUE TITLE
Display blog post titles on blog post pages

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#39]
The blog looks lovely! However, the post titles aren't visible, which I think isn't great from a usability point of view or SEO (no `<h1>` tags).

Can we please add these? Thanks!

**Comment by petermonte** [comment]
@yalisassoon I'm actually encountering an issue that I can't seem to solve on my own. I'm trying to reach the [post title](https://github.com/snowplow/snowplowanalytics.com/blob/develop/_layouts/post.html#L12) from the var `title` but it doesn't seem to print anything.

**Comment by yalisassoon** [comment]
Looking at our [old website](https://github.com/snowplow/snowplow.github.com/blob/master/_layouts/post.html#L12-L13) maybe you need to change `title` to `page.title`?

**Comment by petermonte** [comment]
Ouch @yalisassoon that makes sense. The title is actually defined on the header block therefore it is access via `page` and not `post`. Thanks
