### ISSUE TITLE
No "recent releases" listed on right hand menu of blog

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#40]
![image](https://cloud.githubusercontent.com/assets/201147/24793742/d5907b7a-1b8b-11e7-9408-398ea2abfd4e.png)

**Comment by petermonte** [comment]
This implementation was actually a simple copy paste from previous site to new site. You can see that the [code](https://github.com/snowplow/snowplowanalytics.com/blob/develop/_includes/blog/sidebar.html#L4) is requesting the recent posts. Is there any configuration from old site that we are missing here?

**Comment by yalisassoon** [comment]
Hey @petermonte - I don't think so because I can see that the most recent releases post can be fetched [here](https://next.snowplowanalytics.com/resources/blog/releases/). So expect we just need to see how it's done there and follow the same approach on the menu?

**Comment by petermonte** [comment]
I've seen the template code and the [line](https://github.com/snowplow/snowplowanalytics.com/blob/develop/_includes/blog/sidebar.html#L4) that feeds that block is counting with a category called "Releases" - `for post in site.categories.Releases limit:10`

Now is this a Jekyll configuration that lists all recent categories or posts? Or is this a manual insertion of a category that determines if the post is to be included as recent?

**Comment by yalisassoon** [comment]
Manually assigning a post as a "Release" post: we do this for any post that describes a new version of any software we publish e.g. http://snowplowanalytics.com/blog/2017/04/11/snowplow-python-analytics-sdk-0.2.0-released/.

Does that answer your question? Or have I misunderstood it?

**Comment by petermonte** [comment]
@yalisassoon I picked up that file form old website. Really don't understand why it is not working.

**Comment by yalisassoon** [comment]
If we can't get it fixed let's remove it from the v1 and create a ticket to add it back down the line?

**Comment by petermonte** [comment]
@yalisassoon this is fixed.
