### ISSUE TITLE
Add resources page

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#41]
Currently this doesn't exist:

![image](https://cloud.githubusercontent.com/assets/201147/24793832/294211f2-1b8c-11e7-9760-1b3cd9f57286.png)

All this needs to do is have links through to the Community (discourse) and blog.

Alternatively we could remove the page, in which case people clicking on the menu item would only open up a submenu. I don't think that that is ideal, but open to it for the v1.

**Comment by jorgemgoncalves** [comment]
We've removed the click and pointer from the Resources option on the menu, now it only opens the submenu
