### ISSUE TITLE
Update CSS on jobs pages so when bold is used in job descriptions it renders on website

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#417]
From Miriam:

> I posted a job ad earlier through Greenhouse which had each paragraph heading in bold. However, when it went live onto our website the text hasn't stayed bold. Could you let me know why this has happened and how to fix it please?

According to the Greenhouse team:

> What our team found is that something in your css file is overriding the "font-weight: bold" style with "font-weight: 400." 

![image](https://user-images.githubusercontent.com/201147/33944896-5f8f6b44-e015-11e7-8f3f-96c79e2e49e3.png)

> What we recommend is that you have someone on your dev team (who has developer permissions in Greenhouse) review the CSS file that you have uploaded to your Configure Job Board page. Let me know if you have any questions and I will be more than happy to help out!

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon our Greenhouse account has been disabled. Can you please create us a new account for us to solve this issue?

Thank you.

**Comment by yalisassoon** [comment]
Hi @jorgemgoncalves - apologies for that - your account has been re-activated

**Comment by jorgemgoncalves** [comment]
Hi guys, this issue was solved directly on the CSS file uploaded on Greenhouse.
