### ISSUE TITLE
Add 404 page

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplowanalytics.com#42]
The S3 hosting uses a page called `error.html` for all invalid paths.

cc/ @yalisassoon

**Comment by yalisassoon** [comment]
Yes!

**Comment by yalisassoon** [comment]
Hey @jorgemgoncalves - is there a simple html page you can quickly pull together for the 404 that's on-brand? If necessary we can push a graphic treatment to a later version and launch with a purely textual page.

**Comment by yalisassoon** [comment]
So we have a lovely 404 page [here](https://next.snowplowanalytics.com/404/index.html). How do we ensure that any incorrect URL e.g. https://next.snowplowanalytics.com/nonsense forwards to this? Is it a Jekyll thing @petermonte, or a hosting thing @jbeemster?

**Comment by jbeemster** [comment]
Right so as I mentioned above the 404 page is currently mapped to `error.html`.  So either we can move that page to the root of the project and name it `error.html` and it will work - or I can change the mapping with how the site is hosted to point at the location that has been setup.

**Comment by jbeemster** [comment]
Also on the 404 page the button to Visit our Homepage actually points to the 404 page instead of the homepage.

**Comment by jbeemster** [comment]
I changed the path in S3 - all working now.

**Comment by jorgemgoncalves** [comment]
I've placed "Visit our Homepage" inside a button and corrected it and now points to the homepage.
I believe everything is ok for launch.

**Comment by dmpacheco** [comment]
@yalisassoon Should the 404 say "Woops! Request a demo."?

**Comment by jorgemgoncalves** [comment]
@dmpacheco Woops! I've committed this correction just now. Obrigado.

**Comment by dmpacheco** [comment]
@jorgemgoncalves Is that commit still pending? Seems that the error is still on both live version and develop. Obrigado!

**Comment by yalisassoon** [comment]
Reopening pending confirmation from @jorgemgoncalves

**Comment by jorgemgoncalves** [comment]
@yalisassoon I hadn't pushed the commit. It is now corrected in the Develop branch.
