### ISSUE TITLE
Look at way of better pushing our white papers

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#424]
The whitepapers that we have on https://snowplowanalytics.com/products/snowplow-insights/ are often missed by prospects.

Can you come up with some suggestions for making these more accessible?

**Comment by yalisassoon** [comment]
Let's discuss this today @jorgemgoncalves - we have some more ideas about white papers, e-books and topic-specific landing pages

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon and @Mandelliant we weren't happy with our previous suggestions and created this final versions:

https://drive.google.com/file/d/1G0IuhWSp22RJYVG1dBs94eOSOP4NoH98/view
https://drive.google.com/file/d/1GgqG64YWInctIpzMxD6eWwR7dP4AAa3a/view

Can we fire it up?

**Comment by yalisassoon** [comment]
Yes please! Fire it up

**Comment by yalisassoon** [comment]
Should be done next week!

**Comment by yalisassoon** [comment]
Expect a PR today!
