### ISSUE TITLE
Customers section - navigation for launch

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#43]
Because at launch we'll only have two case studies (JustWatch and Simply Business) it doesn't make sense to divide case studies into ad tech vs publishing vs gaming etc.

Instead I think we just need to have:

1. An overview page (https://next.snowplowanalytics.com/customers/) with the long list of logos added
2. The Simply Business case study, which is linked through from the overview page. (And if categorised, is categorised as "retail".
3. The JustWatch case study, which is linked through from the overview page. 

I don't think it makes sense having a submenu for customers until we have a few more case studies and want to organise them by industry. (Which we will want to do soon.)

**Comment by jorgemgoncalves** [comment]
@yalisassoon I believe this issues is sorted right?

**Comment by yalisassoon** [comment]
Sorted! Closing
