### ISSUE TITLE
JustWatch case studies: fix images and formatting

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#44]
The first version of the JustWatch case study can be found here: https://next.snowplowanalytics.com/customers/ad-tech/.

We need to:

#### A. Update the graphics. We could use screenshots from JustWatch, or from slides from the [JustWatch presentation at the Snowplow Meetup Berlin](http://snowplowanalytics.com/blog/2017/01/31/roundup-of-snowplow-meetup-berlin-number-three/) e.g. this from slide 8:

![image](https://cloud.githubusercontent.com/assets/201147/24798278/c8606160-1b9d-11e7-80c7-0ad58b43a481.png)

#### B. Tweak the CSS so it all looks nice on the page

Like the other pages.

#### C. Get the link to download the case study to a version of the attached

This is the current version of the case study. It hasn't been formatted as per our new brand :smile:

[JustWatch case study_v8.docx](https://github.com/snowplow/snowplowanalytics.com/files/905383/JustWatch.case.study_v8.docx)

Note that we are checking that the JustWatch guys are happy with the case study at the moment.

#### D. Fix the URL

Currently this is the ad-tech URL.

**Comment by yalisassoon** [comment]
Let me know if I should break this ticket into multiple tickets @jorgemgoncalves (and if I should assign to someone else). Thought it would be helpful to think about the case study holistically.

**Comment by jorgemgoncalves** [comment]
This page has been updated, please review.

**Comment by yalisassoon** [comment]
Looks great! Closing
