### ISSUE TITLE
Take pricing section off the website

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#459]
We want to rearchitect our pricing so for the moment it'd be good to remove this section on https://snowplowanalytics.com/products/snowplow-insights/:

![image](https://user-images.githubusercontent.com/201147/34571055-776f1230-f165-11e7-8a31-d257c5b0d6a3.png)

**Comment by jorgemgoncalves** [comment]
Pricing is already removed from Snowplow Insights page.
