### ISSUE TITLE
Footer Behaviour / Columns

### ISSUE THREAD

**Issue by dangregorio** [snowplow/snowplowanalytics.com#46]
@yalisassoon We need to redesign the footer to reduce the number of columns to match Bootstrap and to optimise the responsive behaviour.

Our suggestion is to make the first column (where the SPW logo is)  the Company column, avoiding an extra column for this.

The "About us" and "Contact Us" become links in a sentence below the logo.

Please see attached image and give us feedback.
![snowplow-footer](https://cloud.githubusercontent.com/assets/26771127/24799473/26104164-1b93-11e7-8d24-8152ed2e8c78.png)

**Comment by yalisassoon** [comment]
Sounds good!
