### ISSUE TITLE
Integrate demo and contact form with Salesforce

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#48]
We'll need to schedule a session with someone from Monarqa and @bogaert to explain how to get this working. (Hopefully not too difficult.)

**Comment by yalisassoon** [comment]
@jorgemgoncalves let me know who from your side should speak to @bogaert and I'll introduce you via email.

**Comment by bogaert** [comment]
Chasing. Can we set a date and time?

**Comment by yalisassoon** [comment]
@jorgemgoncalves @petermonte can you let us know who from your side needs to be on a call and when would be convenient? Keen to get this scheduled as it's a core piece of functionality 😄

**Comment by bogaert** [comment]
@jorgemgoncalves @petermonte who do we need to set up call with? We need to set aside time for this and the sooner we hear something the better.

**Comment by jorgemgoncalves** [comment]
@yalisassoon @bogaert i would suggest monday morning? Is that good for you?

**Comment by yalisassoon** [comment]
Monday's a bank holiday in the UK @jorgemgoncalves. (I guess not in Portugal?) Would Tuesday be possible?

**Comment by jorgemgoncalves** [comment]
Here the bank holiday is tomorrow 😂 . Tuesday, no problem! 10:30?

**Comment by bogaert** [comment]
Thanks @jorgemgoncalves, I sent an invite for 10:30 on Tuesday. Have a great weekend!

**Comment by bogaert** [comment]
Following up on our conversation: we'll need separate first name and last name fields. Ping us when that's done and @dilyand will update the Javascript and Salesforce/Snowplow integration.

**Comment by jorgemgoncalves** [comment]
Hi @bogaert. We've already added the required fields. Please check ir everything is ok.

**Comment by bogaert** [comment]
Thanks! We're testing the forms now.

**Comment by yalisassoon** [comment]
Adding @bogaert and @dilyand as assignees. We're hoping to launch tomorrow - do you think you'll have an opportunity to complete the testing tomorrow?

Thanks!

**Comment by bogaert** [comment]
Probably not. The schemas haven't been deployed yet.

**Comment by yalisassoon** [comment]
Adding @jbeemster to the thread - @jbeemster anyway we can get the relevant schemas deployed tomorrow? Keen to launch the new website tomorrow if possible...

Thanks!

**Comment by bogaert** [comment]
There's a thread open in L3 Tech Ops. Let's keep the discussion there.

**Comment by yalisassoon** [comment]
@dilyand just to confirm this all works and this issue can be closed?

**Comment by dilyand** [comment]
@yalisassoon Confirmed.   

--- Sent on the move

Original Quoted context has been removed as per policy

**Comment by yalisassoon** [comment]
Just tested these and I don't think they're working I'm afraid. I no longer get redirected to the thank you page - I get stuck on the following:

![image](https://cloud.githubusercontent.com/assets/201147/25349160/b7ed8f82-2918-11e7-98ef-fc45ef39ffd1.png)

from the demo (URL https://www.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8), and the following from the contact page:

![image](https://cloud.githubusercontent.com/assets/201147/25349198/dae33906-2918-11e7-954a-e37497a50e8a.png)

URL: https://www.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8

**Comment by yalisassoon** [comment]
Just confirmed and I get the above behaviour on next.snowplowanalytics.com and the website when I run it locally.

**Comment by dilyand** [comment]
@yalisassoon These were both working fine locally and on next.snowplowanalytics.com when I tested them. I'm looking for anything that may have changed in the meantime, but so far haven't found anything.

**Comment by dilyand** [comment]
@yalisassoon the events are getting through into Salesforce. I just have to figure out why the redirect is not working.

**Comment by yalisassoon** [comment]
Figured this out: https://github.com/snowplow/snowplowanalytics.com/commit/fced53cac2e150769efa1426c7a21fbd2f03645a

Creating a ticket so that in a future version we set this dynamically. (So on next.snowplowanalytics.com the thank you page is served from there rather than hard coded to the production site.)
