### ISSUE TITLE
Can we line up buttons when we have two equivalent units next to each other?

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#50]
E.g. [here](https://next.snowplowanalytics.com/products/snowplow-open-source/):

![image](https://cloud.githubusercontent.com/assets/201147/24800276/23a6a71e-1ba8-11e7-921f-3e10568092b6.png)

It would be nice to line up the "Learn more" buttons, and

[here](https://next.snowplowanalytics.com) on the homepage:

![image](https://cloud.githubusercontent.com/assets/201147/24800328/52be5ace-1ba8-11e7-8a09-23b4d99033bc.png)

and [here](https://next.snowplowanalytics.com/products/) on the product page:

![image](https://cloud.githubusercontent.com/assets/201147/24800372/83f4c074-1ba8-11e7-8c2c-0b7e0853a263.png)

What do you think?

**Comment by jorgemgoncalves** [comment]
@yalisassoon we've already lined up all the buttons.
