### ISSUE TITLE
Visual call to action for blog posts

### ISSUE THREAD

**Issue by Mandelliant** [snowplow/snowplowanalytics.com#511]
We would like a series of different visual call to action buttons/elements that we can use at the end of blog posts. CTAs like a simple button like the email subscription button on the community page or an image banner promoting the product analytic series, for example.

Possible CTAs:
- Subscribe to our newsletter
- Contact us
- Request a demo 
- Get the latest in our product analytics series
- Read the case study

**Comment by yalisassoon** [comment]
Similar ticket here: https://github.com/snowplow/snowplowanalytics.com/issues/293.

**Comment by jorgemgoncalves** [comment]
Hi, @yalisassoon and @Mandelliant we've come up with this module:

https://drive.google.com/file/d/1cSgtloOW2Ond2YyN4jbOIXSVknbBKhig/view?usp=sharing

What do you think?

**Comment by yalisassoon** [comment]
From @Mandelliant - if we can make the following static:

* Subscribe to our newsletter
* Contact us
* Request a demo

Let's get these quick!

With the others it'd be nice to have the ability to change the text but also modify what the button does e.g. "Download the ebook"

**Comment by yalisassoon** [comment]
@jorgemgoncalves - solution - code snippet:

* title field
* copy field
* CTA field - two options: 
  - copy 
  - link that it'll send to

**Comment by yalisassoon** [comment]
@jorgemgoncalves to get back to us - hopefully this will be delivered mid-end of next week

**Comment by yalisassoon** [comment]
@jorgemgoncalves any update on this?

**Comment by jorgemgoncalves** [comment]
hi @yalisassoon we prioritized the website performance tasks and therefore this one is still in development. I believe it will be finished in the next couple of days.

**Comment by Mandelliant** [comment]
Awesome @jorgemgoncalves, I'm excited to give these a try

**Comment by jorgemgoncalves** [comment]
Hello @Mandelliant and @yalisassoon, I've just merged the Visual Call to Action to QA.

Can you please do some tests on your side and check if everything is running correctly and that you understand how it works.

To add a Call to Action on a page you can use the following:

Contact Us - {% include shortcodes/contact-us.html %}
Request Demo - {% include shortcodes/request-demo.html %}
Subscribe Box - {% include shortcodes/subscribe.html %}
Dynamic Box - {% include shortcodes/dynamic.html title="TITLE GOES HERE." description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua." btnText="Button Test" link="#" %}

To use the Call to Actions in blog posts you just need to add the tag “layout=blog” to the shortcodes: 

Contact Us - {% include shortcodes/contact-us.html layout="blog" %}
Request Demo - {% include shortcodes/request-demo.html layout="blog" %}
Subscribe Box - {% include shortcodes/subscribe.html layout="blog" %}
Dynamic Box - {% include shortcodes/dynamic.html layout="blog" title="TITLE GOES HERE." description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua." btnText="Button Test" link="#" %}

When adding them to blog posts be sure not to give any breaks or spacings before of after the shortcodes.

Any doubts don't hesitate to ask.

**Comment by jorgemgoncalves** [comment]
Hi @Mandelliant, I see you've already made the PR to next.snowplowanalytics.com! Was everything working as you wished?

**Comment by yalisassoon** [comment]
These look great! Closing
