### ISSUE TITLE
Case Studies: add downloadable PDF for JustWatch case study.

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#52]
I've [attached the current version of the long form case study](https://github.com/snowplow/snowplowanalytics.com/files/909120/JustWatch.case.study_v5.docx). note that the JustWatch team are currently reviewing this, so it is subject to change. (Though likely to be wording rather than substantive.)

Can we please:

- [x] Format the doc so it is branded appropriately
- [x] Generate PDF and add to website
- [x] Update download button on case study page so that it grabs a copy of the doc

Thanks!

[JustWatch case study_v5.docx](https://github.com/snowplow/snowplowanalytics.com/files/909120/JustWatch.case.study_v5.docx)

**Comment by yalisassoon** [comment]
We have a later version of the case study - attaching here:

[JustWatch case study_v10.docx](https://github.com/snowplow/snowplowanalytics.com/files/915375/JustWatch.case.study_v10.docx)

**Comment by jorgemgoncalves** [comment]
@yalisassoon uploaded the new pdf and placed the button on the page. Please review.

**Comment by yalisassoon** [comment]
Looks great! Closing
