### ISSUE TITLE
Email templates

### ISSUE THREAD

**Issue by Mandelliant** [snowplow/snowplowanalytics.com#530]
Create three different HTML email templates to use in marketing campaigns:

1. Regular recurring blog newsletter
2. Special announcements
3. Mostly visual CTA emails (subscribe, download, request a demo)

**Comment by Mandelliant** [comment]
Anthony to provide some example emails

**Comment by yalisassoon** [comment]
This will be higher priority once Chih is onboard.

**Comment by jorgemgoncalves** [comment]
Hi @Mandelliant, can you send me the email template that you have been using or access to Mailchimp so that we can take a look?

**Comment by jorgemgoncalves** [comment]
Sorry @Mandelliant it didn't reach its final destination 😢. Can you please resend it?

**Comment by Mandelliant** [comment]
@jorgemgoncalves sent!

**Comment by Mandelliant** [comment]
@jorgemgoncalves the base template you've created is a great start! Chih is on board now and once we finish the eBook and taking care of GDPR tasks, we'll have him on a call to go over what we'd like out of templates in greater detail

**Comment by Mandelliant** [comment]
Adding @Chi112

**Comment by Mandelliant** [comment]
done (handled in Pardot)
