### ISSUE TITLE
Finalize layout for SimplyBusiness case study page

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#54]
Not sure what the best images to use might be?

/customers/simplybusiness/

Some things we might want:

1. Picture of Stewart Duncan or Dani Sola
2. Screenshots of the Simply Business website

**Comment by ggaviani** [comment]
here is the picture of Stewart Duncan we have used for the case study:
https://drive.google.com/open?id=0BxJoshguPkc4QXljRGlDN0E5QVU

**Comment by jorgemgoncalves** [comment]
Page updated, please review

**Comment by yalisassoon** [comment]
LOVE IT! Closing
