### ISSUE TITLE
Finalize layout and images for JustWatch case study 

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#55]
The content is done! Now we just need to finalize the images and the layout.

We might want to take screenshots from the JustWatch website and images from the [slide deck they delivered in Berlin](http://snowplowanalytics.com/blog/2017/01/31/roundup-of-snowplow-meetup-berlin-number-three/)

**Comment by yalisassoon** [comment]
This might be a good image:

![image](https://cloud.githubusercontent.com/assets/201147/24848842/7846fb40-1dd1-11e7-99cf-32a774247510.png)

Taken from slide 8 of their deck

**Comment by jorgemgoncalves** [comment]
We've updated this page, please review.

**Comment by yalisassoon** [comment]
LOOKS AWESOME! Closing...
