### ISSUE TITLE
Homepage - Snowplow Insights Intro

### ISSUE THREAD

**Issue by jorgemgoncalves** [snowplow/snowplowanalytics.com#56]
@yalisassoon what do you think about changing the Snowplow Insights intro from: 

_"For decades, across a range of sectors, many companies have used data to drive sustained competitive advantage. Digital platforms and technology create new opportunities to use data."_

to

_"Take control of your data collection. You decide what you want track. We deliver that data to you!"_

**Comment by yalisassoon** [comment]
Hey @jorgemgoncalves - which web page are you referring to? I can't see any that say 

> For decades, across a range of sectors, many companies have used data to drive sustained competitive advantage. Digital platforms and technology create new opportunities to use data.

I thought we got rid of that copy a while back but let me know if I missed it and it lives on somewhere... I can't see it [here](https://next.snowplowanalytics.com/products/snowplow-insights/)?

**Comment by yalisassoon** [comment]
Sorry - I didn't read the title :-). Yes - I'm going to update the homepage content now - it definitely needs updating. (Not sure how I missed that...)

**Comment by yalisassoon** [comment]
I've updated the copy now - will have a look with fresh eyes tomorrow 😄
