### ISSUE TITLE
Add additional users to users page

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#57]
* https://www.ivcbrasil.org.br/
* http://www.secretsaucepartners.com/
* http://makerist.de/
* https://www.unilever.com/
* https://codecombat.com/
* https://www.moviestarplanet.com/
* https://incrowdsports.com/
* https://simbasleep.com/

**Comment by jorgemgoncalves** [comment]
Additional users already placed in users page.
