### ISSUE TITLE
Add updated pricing back to Snowplow Insights page

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#573]
Please find the updated pricing attached.
Can we get this put on the Snowplow Insights page please?
If we can get this prioritised that would be awesome!
Many thanks
[Pricing summary - March 2018.pdf](https://github.com/snowplow/snowplowanalytics.com/files/1802133/Pricing.summary.-.March.2018.pdf)

**Comment by yalisassoon** [comment]
Jorge to send me the branch name so I can update the text

**Comment by yalisassoon** [comment]
PR should be forthcoming v soon!

**Comment by yalisassoon** [comment]
Can we have a new PR please? The current one has a load of other updates that have "bled in".

I've attached the updated text - if this can be included in the PR that would be great.

Have also sent a separate email to @jorgemgoncalves 

Thanks!
[Pricing summary - March 2018.pdf](https://github.com/snowplow/snowplowanalytics.com/files/1913119/Pricing.summary.-.March.2018.pdf)

**Comment by yalisassoon** [comment]
Hi @jorgemgoncalves - any update on when this can be done please? Hopefully it's simple and would make a big impact on us commercially!

Thanks...

cc @Mandelliant

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon, sorry I didn't put you up to date of our last meeting.

I had already created a new branch and updated with the copy you sent. I've merged it with QA for you guys to check it out.

If you'd like I can create a merge with next.

**Comment by yalisassoon** [comment]
Hey @jorgemgoncalves - if you create a PR into next that would be great! I can take it from there.

Thanks

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon, created PR #646. Please check if it's ok to merge. 

Thank you.
