### ISSUE TITLE
Production Snowplow JS Tracker: switch to using 1EnpRtX3m0Mi45LjA.js

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplowanalytics.com#574]
Presumably this will help improve tracking of leads from users with AdBlockers.

Please leave the QA tracker (snplow6 etc) as-is as we use this for canary testing of new JS Tracker release candidates.

/cc @dmpacheco 

```
    | ======= | ================================================== | 
    | Version | Distribution URL                                   | 
    | ------- | -------------------------------------------------- | 
    | 2.9.0   | d1ojt2gpaejx54.cloudfront.net/1EnpRtX3m0Mi45LjA.js | 
    | ======= | ================================================== | 
```

**Comment by paulboocock** [comment]
As we no longer host sp.js on cloudfront, when we put 2.12.0 on GTM we have ended up doing this.
