### ISSUE TITLE
Can we update comments so that we don't have the Snowplow logo there?

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#591]
It looks out of place:

<img width="838" alt="image" src="https://user-images.githubusercontent.com/201147/37715475-ff3e0196-2d13-11e8-9e14-7333f9ab0456.png">

**Comment by yalisassoon** [comment]
@jorgemgoncalves already spoken to development team to see if this can be resolved. it cna be solved so will be done!

**Comment by jorgemgoncalves** [comment]
We've removed the logo from the discourse embedded comments and also gave a nicer look to the Continue Discussion button.

**Comment by jorgemgoncalves** [comment]
This is working on the production website. Closing
