### ISSUE TITLE
Grammatical error on blog post 

### ISSUE THREAD

**Issue by Charliescott** [snowplow/snowplowanalytics.com#596]
https://snowplowanalytics.com/blog/2018/02/02/data-driven-product-development-is-more-about-process-culture-and-people-than-technology/

Spotted this small error:

"What does successful use of data to drive the product development process like?"

Should be "... development process look like?" 

Thanks

**Comment by Mandelliant** [comment]
Thanks, @Charliescott, will take care of this!

**Comment by Mandelliant** [comment]
Resolved with https://github.com/snowplow/snowplowanalytics.com/pull/604
