### ISSUE TITLE
Fix link to Terms of Service in footer

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplowanalytics.com#6]

**Comment by petermonte** [comment]
@alexanderdean Is there a Terms of Service page?

**Comment by alexanderdean** [comment]
Not sure - @yalisassoon ?

**Comment by yalisassoon** [comment]
No - we should write one...

**Comment by jorgemgoncalves** [comment]
@yalisassoon We've created a simple page and places the link on the footer, you just need to modify the content.
