### ISSUE TITLE
Fix overlapping buttons on Discourse

### ISSUE THREAD

**Issue by dilyand** [snowplow/snowplowanalytics.com#605]
On some screens the search bar overlaps with the Community menu item, make the search bar unusable.

<img width="1170" alt="screen shot 2018-03-23 at 10 04 32" src="https://user-images.githubusercontent.com/22545434/37823681-1bdc6f12-2e82-11e8-9f4c-1e69ed95f850.png">

**Comment by Mandelliant** [comment]
Thanks for spotting this, @dilyand - I'll work with Jorge to get it resolved.

**Comment by jorgemgoncalves** [comment]
Hi @dilyand and @Mandelliant we've tweaked the CSS the menu doesn't overlap in wider screens.

Can you please check?

**Comment by Mandelliant** [comment]
I've checked on Chrome and Firefox on desktop, and Chrome on mobile and tablet and haven't seen an overlap, so it looks good from my perspective. @dilyand let us know if you're able to recreate the issue.

**Comment by dilyand** [comment]
Looks fine for me on the big screen now. Thanks!

**Comment by jorgemgoncalves** [comment]
Thanks for the feedback. Closing.
