### ISSUE TITLE
Discoure link missing from the bottom of blog posts

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplowanalytics.com#61]
At the bottom of all of our blog posts we have a link to discourse: http://snowplowanalytics.com/blog/2017/04/13/how-justwatch-uses-snowplow-case-study/

**Comment by yalisassoon** [comment]
We do this so users can comment on posts / continue the discussion on our Discourse

**Comment by jorgemgoncalves** [comment]
We've already placed the link and we are going to style the Author box.
