### ISSUE TITLE
Update image so we don't have Google Analytics (competitor)

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#62]
The following screenshot is from Google Analytics:

![image](https://cloud.githubusercontent.com/assets/201147/25019925/1901a83a-2095-11e7-9343-9f9711383682.png)

We should replace it - ideally with a screenshot of a BI tool on top of Snowplow data. (I can share some links.)

**Comment by jorgemgoncalves** [comment]
@yalisassoon That would be great! Can share them here directly please?

**Comment by colmsnowplow** [comment]
@jorgemgoncalves - See below, I have also emailed you the files. @yalisassoon let me know if these aren't what you had in mind and I'll take different ones.

![codecombat_level_dash](https://cloud.githubusercontent.com/assets/25744626/25135042/177e5172-2449-11e7-986d-9c52c720e303.jpeg)
![codecombat_level_dash_2](https://cloud.githubusercontent.com/assets/25744626/25135047/1a43dad0-2449-11e7-8286-e78cfb5c2a50.jpeg)
![retail_looker_dash](https://cloud.githubusercontent.com/assets/25744626/25135048/1bd7255a-2449-11e7-9029-e699e944059f.jpeg)

**Comment by bogaert** [comment]
We'll need something a lot simpler. On what pages will this asset be used?

**Comment by colmsnowplow** [comment]
I think it's just to replace the one image above that happened to be a screenshot of GA.

**Comment by bogaert** [comment]
That I know. But that picture is currently used on multiple pages - including the JustWatch and Simply Business case studies - so I assume it's a placeholder for something else. Do we want something that vaguely relates to JustWatch on that page? Simply Business?

**Comment by colmsnowplow** [comment]
Oh I see, apologies I thought it was just one instance.

**Comment by colmsnowplow** [comment]
This is a little simpler I think -is this more like what you had in mind?
![retail_looker_dash_2](https://cloud.githubusercontent.com/assets/25744626/25140241/8365e446-2457-11e7-97f7-7c6af2d9131d.jpeg)

**Comment by jorgemgoncalves** [comment]
@yalisassoon we've updated the images on the cases page and considering the screenshots were to complex we replaced the analytics image with a more "inspiring" one. Your thought?

**Comment by jorgemgoncalves** [comment]
We are also going to place the graphic you sent below this text and image block.

**Comment by yalisassoon** [comment]
The new images are great @jorgemgoncalves - very happy with them!
