### ISSUE TITLE
Duplicate "Inside the plow" categories on the blog

### ISSUE THREAD

**Issue by Mandelliant** [snowplow/snowplowanalytics.com#626]
For some reason the "Inside the plow" category is duplicated. Both links return the same result, so identifying the broken page is challenging.

We should figure out which page has the issue and correct it.

<img width="214" alt="inside the plow" src="https://user-images.githubusercontent.com/8901138/38618037-843eb39c-3d66-11e8-866d-a3b28833b2c7.png">

**Comment by jorgemgoncalves** [comment]
Hi @Mandelliant & @yalisassoon, we've already fixed this issues. 
The category is case sensitive so if you capitalize on category and not the other it duplicates the category.

**Comment by alexanderdean** [comment]
This is fixed.
