### ISSUE TITLE
Careers section of website is missing

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplowanalytics.com#63]
(I'd like to rename it from Jobs.)

**Comment by yalisassoon** [comment]
Good point @alexanderdean!

Can we please add this in the Company section on the website?

The page can be super simple. Might be nice to put one of the photos of us all working together in Berlin on the top of it.

**Comment by jorgemgoncalves** [comment]
Careers section added. 

Can you share the photos so that we can add one?

**Comment by yalisassoon** [comment]
The careers section looks good! Let's not worry about a photo at this stage - I'll create another ticket to explore this for the 1.1 release.

thanks!
