### ISSUE TITLE
Add Big Tree as an implementation partner

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#645]
Graphic: Attached both as a vector and png

Tagline: Business Intelligence Meets Digital Growth Implementation

Paragraph: Big Tree provides a holistic action plan based on your business, metrics, customers, and goals. Next, we work with your team to implement solutions, measure them, and grow your business where it counts. Satisfaction guaranteed <3

Callouts: Business Intelligence - Digital Growth Implementation - Digital Marketing - Conversion Optimization - Automated Nurturing - Analytics services - Customer experience services - B2B - Ecommerce - Making you money - Winning happy customers

Location: Iowa, USA

Website URL: https://www.bigtreeonline.com
[BigTree_PressPack_Logos.zip](https://github.com/snowplow/snowplowanalytics.com/files/1935451/BigTree_PressPack_Logos.zip)

cc @Mandelliant

**Comment by Mandelliant** [comment]
addressed in #723
