### ISSUE TITLE
Insecure assets are being loaded on the home page

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplowanalytics.com#65]
Getting a Connection is not Secure error on the HTTPS.

**Comment by yalisassoon** [comment]
Hey @jorgemgoncalves @petermonte - any idea what this is?

**Comment by jbeemster** [comment]
Looking in the debugger console it looks like we are using collectors which do not have HTTPs support.  Seems to be coming from a Snowplow Mini by the looks of it.

**Comment by petermonte** [comment]
I'm going to paste and simplify the code that we're using to load the new website assets. These assets are css and javascript files that are needed for styling and interactive logic:

in header:
```html
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>

<link href="https://fonts.googleapis.com/css?family=Rubik:300,300i,400,400i,700,700i" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Slabo+27px" rel="stylesheet">
```

The rest of the calls are done with local files like in :
```html
<script type="text/javascript" src="{{ BASE_PATH }}/assets/js/snowplow.js"></script>
```

For the moment I can see that in the console there is this error but it is pointing to a `https`:
`https://collector-rt-demo.snplow.com/com.snowplowanalytics.snowplow/tp2 net::ERR_CONNECTION_REFUSED` 

I can also see that in the `_config.yml` file of Jekyll there are some options pointing to urls that are not `https`:

```yaml
production_url : http://snowplowanalytics.com
url : http://snowplowanalytics.com
```

**Comment by yalisassoon** [comment]
Ah - @petermonte - you're absolutely right. The Snowplow collector for our demo account doesn't an the SSL cert attached. @jbeemster is this something we can get sorted today? Otherwise I'll ask @dilyand to remove the demo from the website so as not to generate the insecure warning.

ThankS!

**Comment by yalisassoon** [comment]
Hey @dilyand - I think the easiest thing for launch is if you remove snplow6 from the website and we re-add at a later date when @jbeemster has got the SSL cert working on the demo collector.

Sound like a plan?

**Comment by yalisassoon** [comment]
Looks like this was done so closing! Thanks @dilyand
