### ISSUE TITLE
Update "Product development loop" image

### ISSUE THREAD

**Issue by Mandelliant** [snowplow/snowplowanalytics.com#671]

**Comment by Mandelliant** [comment]
@jorgemgoncalves to modify product development loop image to be in line with Snowplow branding and style guide:



![data driven product development loop 1](https://user-images.githubusercontent.com/8901138/39602657-d2169dac-4ef3-11e8-9425-81b0c7b38128.jpg)

**Comment by jorgemgoncalves** [comment]
Hey @Mandelliant, here is our redesign proposal. Give me your thoughts! 

<img width="555" alt="product development process" src="https://user-images.githubusercontent.com/26622929/40060589-e2e52a54-584e-11e8-9a84-09d5519aa06a.png">

**Comment by Mandelliant** [comment]
@jorgemgoncalves this is AWESOME! I love it!
