### ISSUE TITLE
Chapter 4 visuals

### ISSUE THREAD

**Issue by Mandelliant** [snowplow/snowplowanalytics.com#685]
Anthony will supply sample images/sketches for chapter 4 graphics

**Comment by Mandelliant** [comment]
Cohort analysis:

![cohortanalysis](https://user-images.githubusercontent.com/8901138/40043779-ce5209fa-5825-11e8-9ea3-5ad817b9c6d5.png)

**Comment by Mandelliant** [comment]
Retention analysis:

![retentioncurve](https://user-images.githubusercontent.com/8901138/40043899-2643f998-5826-11e8-935c-4de4c0244523.png)

**Comment by Mandelliant** [comment]
A/B testing:

![ab-testing](https://user-images.githubusercontent.com/8901138/40043950-41097762-5826-11e8-9f76-6f0c49be445b.png)

**Comment by Mandelliant** [comment]
Heat mapping (it might be good to make our example using the Snowplow website):

![heat-map-examples-click-tracking](https://user-images.githubusercontent.com/8901138/40044048-8bf9a742-5826-11e8-9f32-08d10ca3f3a5.jpg)

**Comment by Mandelliant** [comment]
Session replay (a session replay tracks precise mouse movements, so this is a nice graphic):

![session-replay](https://user-images.githubusercontent.com/8901138/40044127-bdb6d656-5826-11e8-9bab-9e3f7ad32b85.jpg)

This is an ugly picture, but shows you what it looks like:

![hotjar](https://user-images.githubusercontent.com/8901138/40044182-eab749d8-5826-11e8-959c-f50414b2bb3e.jpg)

**Comment by Mandelliant** [comment]
Funnel analysis:

![funnel-visualization](https://user-images.githubusercontent.com/8901138/40044212-05e432de-5827-11e8-9d86-dca4f48d6c34.jpg)

**Comment by Mandelliant** [comment]
User survey example 1:

![419481-user-survey](https://user-images.githubusercontent.com/8901138/40044289-3afb1136-5827-11e8-8988-0a7b12adb3f4.jpg)

Example 2:

![ps4_user_survey](https://user-images.githubusercontent.com/8901138/40044296-41038888-5827-11e8-84af-82a0610356c9.png)


Possible graphic inspiration:

![user_surveys-512](https://user-images.githubusercontent.com/8901138/40044313-4982634e-5827-11e8-836d-34a092eb9062.png)

**Comment by Mandelliant** [comment]
Form submission analysis:

![eform-form-submission-stat](https://user-images.githubusercontent.com/8901138/40044420-9a419e76-5827-11e8-97a2-698821ecfe33.jpg)

**Comment by Mandelliant** [comment]
@jorgemgoncalves let me know if you have any questions about these examples

**Comment by jorgemgoncalves** [comment]
Hi @Mandelliant, We're looking at chapter 4 and the images that you shared. 

Is the objective to adapt them to a Branded look or to serve as inspiration to create a specific icongraphy?

**Comment by Mandelliant** [comment]
Hi @jorgemgoncalves, does a minimalist, branded version of the images make sense? 

Here's a very rough sketch of how I imagine each entry on the list looking, with the graphic part being a simple, Snowplow branded image:

![0515181004](https://user-images.githubusercontent.com/8901138/40061771-f6e8c244-5859-11e8-95ab-54caabd34950.jpg)

**Comment by jorgemgoncalves** [comment]
What do you think if we create some icon/graphic in the same line as the ones used in the services page, visually adapted to each point of course!

<img width="947" alt="example" src="https://user-images.githubusercontent.com/26622929/40062346-eb125bb2-5852-11e8-900e-7233029ca181.png">

**Comment by Mandelliant** [comment]
@jorgemgoncalves that's exactly what I had in mind! Let me know if any of these images are challenging, I can find a better example for you

**Comment by Mandelliant** [comment]
done
