### ISSUE TITLE
Typo on careers page ('Entrepeneurial')

### ISSUE THREAD

**Issue by knjk04** [snowplow/snowplowanalytics.com#687]
![1525983587_2119_10 05 2018_](https://user-images.githubusercontent.com/11173328/39892261-f70a738c-5497-11e8-942a-16597f3f01e1.png)

- Mistake: 'Entrepeneurial', instead of 'Entrepreneurial'
`<li>Entrepeneurial and delivery focused?</li>`

- Suggested fix: `<li>Entrepreneurial and delivery focused?</li>`

[Careers URL ](https://snowplowanalytics.com/company/careers/ )

**Comment by Mandelliant** [comment]
Thanks, @knjk04! Great eye! This is fixed in PR https://github.com/snowplow/snowplowanalytics.com/pull/693.
