### ISSUE TITLE
Subject menu empty in Contact us page 

### ISSUE THREAD

**Issue by ggaviani** [snowplow/snowplowanalytics.com#69]
Currently it just has placeholders.

**Comment by bogaert** [comment]
Worth asking Idan what the most common questions are.

**Comment by ggaviani** [comment]
I gathered from Idan that the questions we get via the Contact us page are a variety around what people can do with Snowplow.  There are no recurrent ones apparently.

Here are some ideas as to what to include in the menu items

- What can I do with Snowplow
- Professional services
- Pricing
- Partnering with Snowplow
- Support
- Other

**Comment by yalisassoon** [comment]
Sound like a decent place to start!

**Comment by jorgemgoncalves** [comment]
Can we place these options on the website?

**Comment by yalisassoon** [comment]
Yes please!

**Comment by jorgemgoncalves** [comment]
Done!
