### ISSUE TITLE
Typo on Insights page ('datawarehouse')

### ISSUE THREAD

**Issue by knjk04** [snowplow/snowplowanalytics.com#695]
![1526070386_2126_11 05 2018_](https://user-images.githubusercontent.com/11173328/39945401-41b6eee0-5562-11e8-9c98-f6957d37f111.png)

I think I found another typo:

- 'datawarehouse', instead of 'data warehouse'?

https://snowplowanalytics.com/products/snowplow-insights/

**Comment by Mandelliant** [comment]
Fixed in PR https://github.com/snowplow/snowplowanalytics.com/pull/697
