### ISSUE TITLE
eBook v1 design feedback

### ISSUE THREAD

**Issue by Mandelliant** [snowplow/snowplowanalytics.com#701]
@Mandelliant to leave comments on eBook v1 pdf

**Comment by Mandelliant** [comment]
@jorgemgoncalves I've left comments on the PDF - let me know if you can see them and we can discuss later next week!

**Comment by jorgemgoncalves** [comment]
Hi @Mandelliant we've updated the PDF with the latest version. 

Maybe because of this update your comments are no longer associated with the specific area. Can you please associate them back with the specific area (sorry).

**Comment by Mandelliant** [comment]
@jorgemgoncalves I've resolved all of the comments that have been addressed - it looks like they're all taken care of!

**Comment by Mandelliant** [comment]
done
