### ISSUE TITLE
Typos on Snowplow Insights page

### ISSUE THREAD

**Issue by ggaviani** [snowplow/snowplowanalytics.com#72]
Section Digital data collection is hard - Engagement varies widely 
Current text :
Users don't engage with email, dating services or an banking apps in the same way.

Proposed text (remove "an")
Users don't engage with email, dating services or banking apps in the same way.

Section Digital data collection is hard - Constantly evolving 
Current text :
Digital products and services are constantly evolving, and as they do, data collection to evolve with it. As we bulid understanding, the questions we ask of data are constantly evolving, and with it, so must our data collection.

Proposed text (see text in bold)
Digital products and services are constantly evolving, and as they do, data collection **needs** to evolve with it. As we **build** understanding, the questions we ask of data are constantly evolving, and with it, so must our data collection.

**Comment by yalisassoon** [comment]
Great spots @ggaviani - thanks! Have updated - closing
