### ISSUE TITLE
Blog Post Image head matter update (FB)

### ISSUE THREAD

**Issue by Chira112** [snowplow/snowplowanalytics.com#724]
Hi Anthony,

Please add the image tags to the following blog posts when you have time:

https://snowplowanalytics.com/blog/2012/09/24/what-does-snowplow-let-you-do/?utm_source=Social%20Media&utm_medium=FB%20post&utm_campaign=Facebook

https://snowplowanalytics.com/blog/2012/10/24/web-analytics-with-tableau-and-snowplow/?utm_source=Social%20Media&utm_medium=FB%20post&utm_campaign=Facebook

https://snowplowanalytics.com/blog/2013/01/18/using-snowplow-with-qubit-opentag/?utm_source=Social%20Media&utm_medium=FB%20post&utm_campaign=Facebook

https://snowplowanalytics.com/blog/2013/01/21/working-out-what-data-to-pass-into-your-tag-manager/?utm_source=Social%20Media&utm_medium=FB%20post&utm_campaign=Facebook

https://snowplowanalytics.com/blog/2013/04/12/online-catalog-analytics-with-snowplow/?utm_source=Social%20Media&utm_medium=FB%20post&utm_campaign=Facebook

https://snowplowanalytics.com/blog/2013/06/05/tracking-olark-chat-events-with-snowplow/?utm_source=Social%20Media&utm_medium=FB%20post&utm_campaign=Facebook

https://snowplowanalytics.com/blog/2013/07/10/help-us-build-out-the-snowplow-total-cost-of-ownership-model/?utm_source=Social%20Media&utm_medium=FB%20post&utm_campaign=Facebook

https://snowplowanalytics.com/blog/2014/01/20/the-three-eras-of-business-data-processing/?utm_source=Social%20Media&utm_medium=FB%20post&utm_campaign=Facebook

https://snowplowanalytics.com/blog/2014/03/19/snowplow-and-looker-announce-formal-partnership/?utm_source=Social%20Media&utm_medium=FB%20post&utm_campaign=Facebook

https://snowplowanalytics.com/blog/2014/04/16/identity-stitching-snowplow-vs-google-universal-analytics-kissmetrics-and-mixpanel/?utm_source=Social%20Media&utm_medium=FB%20post&utm_campaign=Facebook

https://snowplowanalytics.com/blog/2014/07/11/on-the-benefits-of-configurable-schemas/?utm_source=Social%20Media&utm_medium=FB%20post&utm_campaign=Facebook

https://snowplowanalytics.com/blog/2014/07/31/using-graph-databases-to-perform-pathing-analysis-initial-experimentation-with-neo4j/?utm_source=Social%20Media&utm_medium=FB%20post&utm_campaign=Facebook

https://snowplowanalytics.com/blog/2015/07/02/visualizing-marketing-attribution-data-with-d3js/?utm_source=Social%20Media&utm_medium=FB%20post&utm_campaign=Facebook

**Comment by Mandelliant** [comment]
done
