### ISSUE TITLE
Typos on Snowplow React page

### ISSUE THREAD

**Issue by ggaviani** [snowplow/snowplowanalytics.com#73]
Section Act On Your Data In Real-time - Third party APIs
Current text
Personalizing a user experience across all of them means working with multiple different APIs and protocols provides significant technical overhead.

Proposed text (see bold)
Personalizing a user experience across all of them means working with multiple different APIs and protocols, **which** provides significant technical overhead.

Section Features - OPTIMIZE YOUR CUSTOMER'S JOURNEY ACROSS ALL MARKETING CHANNELS, 2nd bullet point.
Current text 
Snowplow React enables you to use the intelligence you build, based on data collected across all channels, to personalize and tailor the communication and service you provide across all the channels you engage you users with.

Proposed text (see bold)
Snowplow React enables you to use the intelligence you build, based on data collected across all channels, to personalize and tailor the communication and service you provide across all the channels you engage **your** users with.

**Comment by yalisassoon** [comment]
Great spots / suggestions @ggaviani - have updated accordingly
