### ISSUE TITLE
Emphasise quote in Simply Business case study

### ISSUE THREAD

**Issue by ggaviani** [snowplow/snowplowanalytics.com#76]
The following text, under Data-driven product development, is an actual quote from Stewart, but the initial quote sign (") is missing. I would add that and emphasise the text like in the other quote below (we can zoom...), so it stands out more and it separates it from the text that follows, which I don't think is a quote (the product team run...)

Pretty much everyone at Simply Business uses Snowplow, especially the product development team. They use that continuously, to analyse the user journey and question set".

**Comment by jorgemgoncalves** [comment]
This text block wasn't looking good with 3 paragraph with only 2 line sentences each. 

What do you think if we gathered the first and second quotes in a single quote and place the middle paragraph first? 

The product team run an ongoing A/B testing program on top of Snowplow data, driving systematic improvements to the on-site experience. In addition, they analyze data to identify and improve friction points in their user journeys.

"Pretty much everyone at Simply Business uses Snowplow, especially the product development team. They use that continuously, to analyse the user journey and question set. We can zoom in where in the form users have an issue and then aggregate the data to understand how many people experience that and how much of a friction point that is. That is powerful."

- Stewart Duncan

**Comment by ggaviani** [comment]
@jorgemgoncalves  yes, I can see that. I think what you suggest would look better.

@yalisassoon , what do you think?

**Comment by yalisassoon** [comment]
I like the idea of having it as a single quote separated into two paragraphs with a `...` between the i.e.

> Pretty much everyone at Simply Business uses Snowplow, especially the product development team. They use that continuously, to analyse the user journey and question set... We can zoom in where in the form users have an issue and then aggregate the data to understand how many people experience that and how much of a friction point that is. That is powerful.

We could then format them so that they are completely consistent? (I.e. all italicised or not italicised).

Sound good?

**Comment by ggaviani** [comment]
It sounds good to me.

**Comment by jorgemgoncalves** [comment]
I've made the required changes on the page. What do you think?

**Comment by yalisassoon** [comment]
Looks good! Closing
