### ISSUE TITLE
Fix header id in Snowplow R88 post

### ISSUE THREAD

**Issue by ungn** [snowplow/snowplowanalytics.com#762]
#### Problem
Link to second header at top of the page is broken on blog post due to incorrect header id.

#### Expected
`crossbatch-natural-deduplication` in `<a href="/blog/2017/04/27/snowplow-r88-angkor-wat-released#crossbatch-natural-deduplication">Cross-batch natural deduplication</a>`
[Line 16](https://github.com/snowplow/snowplowanalytics.com/blame/master/_posts/2017-04-27-snowplow-r88-angkor-wat-released/index.md#L16)

#### Actual
`synthetic-dedupe` in `<h2 id="synthetic-dedupe">2. Cross-batch natural deduplication</h2>`
[Line 37](https://github.com/snowplow/snowplowanalytics.com/blame/master/_posts/2017-04-27-snowplow-r88-angkor-wat-released/index.md#L37)

#### Solution
Update id on [Line 37](https://github.com/snowplow/snowplowanalytics.com/blame/master/_posts/2017-04-27-snowplow-r88-angkor-wat-released/index.md#L37) to `crossbatch-natural-deduplication` to fix link.

**Comment by knrt10** [comment]
I would like to work on this.

**Comment by ksandhu16** [comment]
If issue isnt closed can I work on this?

**Comment by knrt10** [comment]
@ksandhu16 sorry to disappoint but Ialready made a PR for the same.
