### ISSUE TITLE
Fix for blog post images for scheduled social media posts

### ISSUE THREAD

**Issue by Chi112** [snowplow/snowplowanalytics.com#764]
https://snowplowanalytics.com/blog/2016/03/16/introduction-to-event-data-modeling/

https://snowplowanalytics.com/blog/2018/02/08/warehousing-google-analytics-data-api-vs-hit-level-data/

https://snowplowanalytics.com/blog/2018/03/09/how-to-manage-consent-for-gdpr-a-nuanced-approach/

https://snowplowanalytics.com/blog/2017/04/12/how-to-develop-better-games-with-level-analytics/

https://snowplowanalytics.com/blog/2017/04/13/how-justwatch-uses-snowplow-case-study/

https://snowplowanalytics.com/blog/2017/03/03/how-peak-uses-snowplow-to-drive-product-development-and-neuroscience/

https://snowplowanalytics.com/blog/2018/04/27/getting-the-most-out-of-product-analytics-with-intelligent-questions/

https://snowplowanalytics.com/blog/2018/01/26/intelligent-use-of-data-in-product-development-differentiates-successful-companies/

https://snowplowanalytics.com/blog/2018/02/02/data-driven-product-development-is-more-about-process-culture-and-people-than-technology/

**Comment by Mandelliant** [comment]
Addressed with PR #768
