### ISSUE TITLE
Blog post rendering issue

### ISSUE THREAD

**Issue by Mandelliant** [snowplow/snowplowanalytics.com#765]
[Loading and analysing Snowplow event data in Neo4j](https://snowplowanalytics.com/blog/2017/07/17/loading-and-analysing-snowplow-event-data-in-Neo4j/) is having an issue building (see screenshot).

<img width="1559" alt="screen shot 2018-06-14 at 11 57 13 am" src="https://user-images.githubusercontent.com/8901138/41423734-1f48432c-6fca-11e8-817a-9bc7d9463dde.png">

**Comment by jorgemgoncalves** [comment]
Hi @Mandelliant, can you please share the name of the branch where the post is?

**Comment by Mandelliant** [comment]
Hi @jorgemgoncalves, this is an old post from 2017 - it's live on master and we don't have the original branch anymore. 

This looks like the original PR: #223

**Comment by Mandelliant** [comment]
@jorgemgoncalves thanks for the update!

**Comment by Mandelliant** [comment]
@jorgemgoncalves solved this
