### ISSUE TITLE
Blog posts not showing images before "continue reading" button

### ISSUE THREAD

**Issue by ggaviani** [snowplow/snowplowanalytics.com#78]
In the current website, blog posts typically show an image (when the post contains one) before the "continue reading" button, which is useful to engage visitors to read on. Have we decided to change the format or is this unintentional?

**Comment by yalisassoon** [comment]
This is deliberate until we've finalized a consistent approach to sizing images, so that the blog roll looks good I believe. @jorgemgoncalves is that right?
