### ISSUE TITLE
Add photo of team working together for the careers section?

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#83]
@bogaert - are there any photos from Berlin that might be good here? If not no worries - let's just close this ticket and create a new one when we have a suitable set of pics.

Thanks!

**Comment by bogaert** [comment]
That's all we have: https://drive.google.com/drive/folders/0B_Ho7UyBmOJnNTU1bWZnTDlwbWc

**Comment by yalisassoon** [comment]
OK - closing this issue
