### ISSUE TITLE
Fix typos in PDFs (comparison papers for Snowplow Insights and case studies) and put live on website

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#84]
Have discussed this in an email thread with @jorgemgoncalves (subject: "Small updates to PDFs")

**Comment by jorgemgoncalves** [comment]
I've updated the files and placed the path on the Insights page.

**Comment by yalisassoon** [comment]
Hi @jorgemgoncalves - that's great! We need to update the drop down on the Insights page so that it triggers a download of the PDFs. (This doesn't seem to be working for me at the moment.)

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon this issue is already solved. The selection automatically opens a tab and presents the PDF.

**Comment by yalisassoon** [comment]
AWESOME! Closing
