### ISSUE TITLE
Add igloo analytics to trusted by page

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#85]
![image](https://cloud.githubusercontent.com/assets/201147/25317859/1accfa3c-288a-11e7-94d2-5f3966daedce.png)

If this can be done for the v1 that's awesome, otherwise put back to v1.1

**Comment by jorgemgoncalves** [comment]
Is there a website for Igloo analytics?

**Comment by yalisassoon** [comment]
Yes! (Sorry should have said.) https://www.iglooanalytics.com/

**Comment by jorgemgoncalves** [comment]
Done. I took the liberty and closed the issue.
