### ISSUE TITLE
Google Analytics screenshot still on our products page /products/

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#86]
![image](https://cloud.githubusercontent.com/assets/201147/25326629/ef5c3bd0-28c8-11e7-8266-7e43b039a3cb.png)

Is there something we can replace it with today? Maybe one of the images [here](https://github.com/snowplow/snowplowanalytics.com/issues/62).

@bogaert don't know if you got the chance to take an alternative? (Take a photo of one of the dashboards on a laptop?)

**Comment by bogaert** [comment]
I can do this tomorrow. Don't have my camera with me today and need daylight.

**Comment by yalisassoon** [comment]
OK cool - I'll move the issue to v1.1 so we're not delayed on our launch 😄

**Comment by jorgemgoncalves** [comment]
I've replaced the photo with another one until we don't have the final one
