### ISSUE TITLE
Can we add the 'BETA' label to the Snowplow React page please?

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#88]
The Insights page doesn't make clear the product is in beta:

![image](https://cloud.githubusercontent.com/assets/201147/25326799/9ae66520-28c9-11e7-8c49-fdddbbdabff7.png)

Unlike the /product/ page where this is made clear:

![image](https://cloud.githubusercontent.com/assets/201147/25326841/c6bdcfda-28c9-11e7-95f7-3bdb3c8f2771.png)

**Comment by jorgemgoncalves** [comment]
BETA added to the header. Please review.
