### ISSUE TITLE
Change the way `app_id` is set in the tracker initialisation tag

### ISSUE THREAD

**Issue by dilyand** [snowplow/snowplowanalytics.com#888]
In our tracker initialisation tags in GTM, we're using the following code to set the value of the `app_id` field:

```
var appId;
  if (hostname == "snowplowanalytics.com") { 
    appId = "website";
  } else if (hostname == "discourse.snowplowanalytics.com") {
    appId = "discourse";
  } else {
    appId = "website-qa";
  };
```

It looks like we've started using additional subdomains, such as `go.snowplowanalytics.com`, so the `app_id` is now being set incorrectly for them.

**Comment by dmpacheco** [comment]
This was fixed in the day it was discovered. Closing.
