### ISSUE TITLE
Update bios with entries that people have put together for themselves

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#91]
@ggaviani please forward these to me so I can add them. (Photos + bios.)

**Comment by ggaviani** [comment]
@yalisassoon , in the links below you will find the team bios I have collected so far (Dilyan, Ben, Keane, Diogo and me) and the team photos (Ben sent two versions).

https://drive.google.com/open?id=1KqWZYsR-5HebLlrU_-9YN7cpvpjLQp4hrhFIYh_pA38

https://drive.google.com/open?id=0BxJoshguPkc4Mkt4NlhfbTlJbXhUeWI2cXFkOTFOZC1yWFpn

https://drive.google.com/open?id=0BxJoshguPkc4VEZwQkRmV1NzMTFsM29WUEJYZVpTRERObGg0

**Comment by yalisassoon** [comment]
Thanks @ggaviani - can you please consolidate all the photos people have sent into a single Google drive folder and share the folder with Jorge and Daniel @ Monarqa?

**Comment by ggaviani** [comment]
@yalisassoon , yes, it is done. 

Hi @jorgemgoncalves and @dangregorio, all our team photos collected so far are in one google drive folder. here is the link:
https://drive.google.com/open?id=0B_Ho7UyBmOJnbG1VVmhITUoxbWM
 
As I receive photos from other team members, I'll save them to the same folder.

**Comment by yalisassoon** [comment]
Done - closing!
