### ISSUE TITLE
Add confirmation pages for when users request a trial or send a message via the contact form

### ISSUE THREAD

**Issue by dilyand** [snowplow/snowplowanalytics.com#92]
The old site has these:

http://snowplowanalytics.com/trial/thanks/
http://snowplowanalytics.com/contact/thanks/

The new one does not seem to have the corresponding pages.

**Comment by yalisassoon** [comment]
Thanks @dilyand - great spot

**Comment by jorgemgoncalves** [comment]
@yalisassoon @dilyand hey guys! Just created the two thank you pages:

http://next.snowplowanalytics.com/company/contact-us/thank-you
http://next.snowplowanalytics.com/request-demo/thank-you

Please give me your thoughts.

**Comment by yalisassoon** [comment]
Looks great!

**Comment by yalisassoon** [comment]
Can we please update the website so that users get forwarded to these beautiful pages after filling in the forms?

Thanks!

**Comment by dilyand** [comment]
@jorgemgoncalves Can you please change the text on the Contact-Us message to read: "Thank you for your message" ?

Otherwise, both are great. I'll make sure the forwarding works.

**Comment by dilyand** [comment]
@yalisassoon The update is waiting to be merged: https://github.com/snowplow/snowplowanalytics.com/pulls

**Comment by dilyand** [comment]
The update has been merged. Now all we need is that slight change to the wording of the first message. It should be:

```
Thank you for your message
```

**Comment by yalisassoon** [comment]
If we can change "Thank you for your message" rather than "Thank you for your message", we're good to close! Thanks

**Comment by jorgemgoncalves** [comment]
@yalisassoon the message was changed to "Thank you for your message".
