### ISSUE TITLE
Move /resources/blog/{{ rest of path }} to /blog/{{ rest of path }}  

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#94]
Hey @jbeemster - I'm breaking down the different redirects that we need to setup. (Hoping this makes things easier to track and manage.) A lot of them can be setup within Jekyll so I've been able to action them directly myself. Hopefully that means I only need to bother you with a handful of additional ones.

One of them that I'm hoping to setup is a rule that redirects any link to:

```
/blog{{ anything else }}
```

to 

```
/resources/blog{{ anything else }}
```

Does that make sense? Is it possible? Is it straightforward?

Thanks!

**Comment by alexanderdean** [comment]
I am really not a fan of putting our blog under a /resources/ sub-folder. It just reads totally wrong to me. The blog is so much more than a "resource".

**Comment by yalisassoon** [comment]
I know what you mean but I don't think it should be a top-level nav item - so the question becomes where should it live.

Can we launch with it in resources and then potentially move?

**Comment by alexanderdean** [comment]
Can it be under Resources in the UX / top-level nav but still in the root from a URI perspective? That pushes the problem back... Any mistake with these redirects (or with taking the blog off a root path in general) could have a huge impact on the site's SEO performance...

**Comment by yalisassoon** [comment]
No idea... @petermonte @jorgemgoncalves any idea?

I'd be surprised if it had a big impact on SEO - it's the same content. And I think there's something nice about the URL following the menu / overall information architecture.

Is setting up the redirect problematic?

**Comment by alexanderdean** [comment]
I believe the redirect would be easy to setup, but I'm not sure losing some or a lot of SEO juice is worth a slightly cleaner mapping from URI resources to UX navigation.

**Comment by jorgemgoncalves** [comment]
@yalisassoon we've moved blog to the root domain. It is still under Resources on the nav but URL wise it's

... /blog ...

 and not 

... /resources/blog ...

**Comment by yalisassoon** [comment]
Great! Closing :smile:

**Comment by alexanderdean** [comment]
Thanks both!
