### ISSUE TITLE
Resources > Community redirects to our forums

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplowanalytics.com#95]
This is a weird bit of UX:

* It's an external link in our main site navigation
* Our forums are an *expression* of our community, but they are not *synonymous* with our community
* Another expression of our community would e.g. be all our meetup groups, https://www.meetup.com/topics/snowplow/

My recommendation:

* For launch, rename Community to "Forums" or "Discourse"
* For after launch, add a proper Community page which has links out to Discourse and Meetup and the other expressions of our community

**Comment by yalisassoon** [comment]
Makes sense @alexanderdean - let's do that. @jorgemgoncalves are you OK to rename "Community" -> "Discourse".

**Comment by jorgemgoncalves** [comment]
Change done!

**Comment by alexanderdean** [comment]
Cool, closing, see #96 for the phase two
