### ISSUE TITLE
Add a community page

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#96]
This should have links to those sites / pages that are expressions of our community including:

* Discourse
* Meetup page(s)

**Comment by jorgemgoncalves** [comment]
Hello @yalisassoon so you would like us to create a page that makes an introduction to your community sites/pages and has links to them, similar to what you had on you previous website?

Let me know it's what you want so I can organize our team on creating a mock up for you to approve and move with creating the page.

**Comment by yalisassoon** [comment]
I need to design what this page will look. (What the content is.)

**Comment by yalisassoon** [comment]
From my perspective - we want the page to link to:

* Discourse 
* Meetup: https://www.meetup.com/topics/snowplow/. Could also link to individual meetup groups
* Github: https://github.com/snowplow or https://github.com/snowplow/snowplow

So not much content to start off with but would be nice to have a good way of presenting it. (We'll also add to it over time.)

**Comment by alexanderdean** [comment]
We have some pinned repos above the fold on https://github.com/snowplow so I think that link is fine

**Comment by yalisassoon** [comment]
This should be where "Resources" is currently - so let's rename the top level menu item from resources -> "Community".

The submenus hsould then match teh three links in the page i.e. discourse/ meetup / github / blog

**Comment by yalisassoon** [comment]
Note we should also update the "Community" link on the homepage to point to this rather than our discourse.

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon, 

We've created a mock up for the Community Page that you can see [here](https://drive.google.com/file/d/0BwwSh8n94UreQUpSeUt0RThueWM/view?usp=sharing).

The idea is that this will work as a masonry grid and will allow adding other sites if needed.

Please share your thoughts.

**Comment by yalisassoon** [comment]
Hi @jorgemgoncalves - I love the design! The text obviously needs some work but as a first version I think this is great.

**Comment by jorgemgoncalves** [comment]
Hi @jbeemster just a quick question! Should we create a new branch from the master to create this new page?

**Comment by yalisassoon** [comment]
PR expected on Monday :smile:

**Comment by yalisassoon** [comment]
Can you view here: https://qa.snowplowanalytics.com/community/.

can't merge yet because fixes to rss feeds are being applied on the same branch.

**Comment by yalisassoon** [comment]
Where are we with the RSS feeds @jorgemgoncalves ? The page looks great - I'm keen to get it merged :smile:

**Comment by yalisassoon** [comment]
Hey @jorgemgoncalves - any update on this? Would be awesome if we can get the new page added, then fix the feeds in a separate PR...
