### ISSUE TITLE
Create notification that the websites uses cookies

### ISSUE THREAD

**Issue by dilyand** [snowplow/snowplowanalytics.com#97]

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon we've created two desktop mockups and a mobile one for this notification message:

![sp_cookie_policy_mobile](https://user-images.githubusercontent.com/26622929/27124648-aef58c6a-50e9-11e7-81bb-a1696579a064.jpg)
![sp_cookie_policy_v1](https://user-images.githubusercontent.com/26622929/27124713-d2905506-50e9-11e7-812f-a357fa1f5f04.jpg)
![sp_cookie_policy_v2](https://user-images.githubusercontent.com/26622929/27124650-af12d798-50e9-11e7-9e09-60097b5bea06.jpg)

We used a standard message that we found online but obviously, the copy can be changed to your desire. 

Will we need to create a page to explain these cookies?

Give you feedback so we can start coding it.

**Comment by yalisassoon** [comment]
Let's link from the warning to our cookie policy: https://snowplowanalytics.com/privacy-policy/.

The text should be:

> We use cookies on this website to track how our users are browing and engaging with it. We use that to figure out how good we are at introducing Snowplow to prospective companies and how well we serve existing users with documentation and other supporting material. For more information [see here](https://snowplowanalytics.com/privacy-policy/).

**Comment by yalisassoon** [comment]
Should be done next week.

**Comment by dilyand** [comment]
Fixed typo:

We use cookies on this website to track how our users are browsing and engaging with it. We use that to figure out how good we are at introducing Snowplow to prospective companies and how well we serve existing users with documentation and other supporting material. For more information [see here](https://snowplowanalytics.com/privacy-policy/).

**Comment by jorgemgoncalves** [comment]
Hi, @dilyand and @yalisassoon, we've uploaded this functionality, but we are still running some tests. If you would like to do some tests from your side that would be awesome. 

Give us your feedback.

**Comment by yalisassoon** [comment]
Hi @jorgemgoncalves ,

Can we update the text so instead of 

> click on the Know more button.ContinueKnow more

We write

> review our [privacy policy](/privacy-policy/)

This should have a hyperlink.

Also - can we either explore another colour or having the message at the bottom rather than the top of the screen? Having the purple up at the top really distracts from the "Request demo" button, which we really want people to click :smile:

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon you are totally right! We're on it. I give you some options as soon as possible.

**Comment by yalisassoon** [comment]
Still in progress

**Comment by dangregorio** [comment]
@yalisassoon We updated the cookie bar colour to make it less distracting. If you still feel necessary, we can change it to the footer.

**Comment by alexanderdean** [comment]
Can we make it say "Learn more" not "Know more"? Know more doesn't make sense in English.

**Comment by dangregorio** [comment]
Done! Please check at https://next.snowplowanalytics.com
Thanks,

**Comment by yalisassoon** [comment]
Looks great! Closing

**Comment by yalisassoon** [comment]
Can we update the last sentence so it says:

> [Click here](https://next.snowplowanalytics.com/terms-of-service/) for more information.

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon i've updated the last sentence as you resquested. I believe this task is done.
